var _version=2;"EVENTSTACK"in window||(window.EVENTSTACK=[]);var objScroll=new Scroll,objPerformance=new Performance,objPing=new Ping,objTools=new Tools,objPWConfig=new pwConfig,nowtime=Math.floor(new Date/1E3),tmpInt=Number(String(Math.random()).slice(2)),hit_id=Number(String(nowtime+tmpInt).slice(0,9)),pingTimerID=0,objEvents=new Events,objEventClick=new EventClick(objEvents),objEventScroll=new EventScroll(objEvents),objEventModel=new EventModel;
objEventModel.subscribe("scroll","main_ab_title",objEventScroll.ObserverABTitle);objEventModel.subscribe("scroll","article_infinity",objEventScroll.ObserverInfinity);objEventModel.subscribe("scroll","article_rcmd_under_article",objEventScroll.ObserverRcmdUnderArticle);objEventModel.subscribe("scroll","article_end",objEventScroll.ObserverArticleEnd);objEventModel.subscribe("click","main_title_ver",objEventClick.ObserverTitleVer);objEventModel.subscribe("click","main_rcmd_floor",objEventClick.ObserverMainRecommendAlg);
objEventModel.subscribe("click","article_rcmd_under_article",objEventClick.ObserverRecommendAlg);objEventModel.import(window.EVENTSTACK);window.EVENTSTACK=objEventModel;window.onload=function(){objTools.hashchangeHandler()};document.addEventListener("DOMContentLoaded",objScroll.setPageHight);document.addEventListener("scroll",objScroll.scroll);window.addEventListener("hashchange",objTools.hashchangeHandler,!1);
function Scroll(){function b(b){for(var f=0;b;)f+=parseFloat(b.offsetTop),b=b.offsetParent;return Math.round(f)}var c=this,m=0,g=0,d=[10,20,30,40,50,60,70,80,90,100],f=d.length,v=null,z=0;this.scrollResult=0;this.setPageHight=function(){m=c.getPageHight()};this.getPageHight=function(){var f=Math.max(document.body&&document.body.scrollHeight?document.body.scrollHeight:0,document.documentElement&&document.documentElement.scrollHeight?document.documentElement.scrollHeight:0,document.body&&document.body.offsetHeight?
document.body.offsetHeight:0,document.documentElement&&document.documentElement.offsetHeight?document.documentElement.offsetHeight:0,document.body&&document.body.clientHeight?document.body.clientHeight:0,document.documentElement&&document.documentElement.clientHeight?document.documentElement.clientHeight:0),d,c=0;if(window.jQuery){var g=$("div.mia-analytics");$("div").is(".mia-analytics")&&(d=g.offset().top,g=g.outerHeight(),c=Math.round(d+g))}else(c=wa("mia-analytics"))&&c[0]&&"object"==typeof c&&
(c=c[0],d=b(c),g=c.clientHeight),c=d+g;return(d=c)&&10<d?d:f};this.scroll=function(){g=window.pageYOffset||document.documentElement.scrollTop;g+=window.innerHeight;if(0<m){var b=Math.ceil(100/(m/g));b>z&&(z=b,clearTimeout(v),v=setTimeout(I,100))}};this.longArticle=function(){var b=this.getPageHight(),b=Math.floor((b-100)/window.innerHeight);0>b&&(b=0);return b};this.visualization=function(){console.log("Analytics GO");var c=document.getElementById("analytics-scala");c&&"object"==typeof c&&c.parentNode.removeChild(c);
c=wa("mia-analytics")[0];if(!c||"object"!=typeof c&&10>=c.offsetHeight)c=document.body;console.log("Canvas GO");var g=document.createElement("canvas"),m=g.getContext("2d"),w=b(c);console.log("TOP",w);g.height=c.offsetHeight+35;g.width=document.body.offsetWidth;g.id="analytics-scala";g.style.position="absolute";g.style.top=w+"px";g.style.zIndex="9999";document.body.appendChild(g);m.strokeStyle="#ff0000";m.fillStyle="#ff0000";m.font="bold 30pt Arial";m.moveTo(0,1);m.lineTo(g.width,0);m.fillText("0%",
0,35);m.stroke();for(w=0;w<f;w++){var v=Math.ceil(d[w]/100*c.offsetHeight);m.moveTo(0,v);m.lineTo(g.width,v);m.fillText(d[w]+"%",0,v+35);m.stroke()}};var I=function(){var b=0;if(c.getPageHight()!=m)return c.setPageHight(),!1;if(z>c.scrollResult)for(var g=0;g<=f;g++)if(z>=d[g])b=d[g];else break;0<b&&(c.scrollResult=b)},wa=function(b){var c=[];if(document.getElementsByClassName)c=document.getElementsByClassName(b);else{var d=document.body.getElementsByTagName("div"),f=d.length,c=[],g;for(g=0;g<f;g+=
1)-1!=d[g].className.search("\\b"+b+"\\b")&&c.push(d[g])}return c}}
function Performance(){this.params={navigation_type:0,timing_full_response:0,timing_dns:0,timing_download:0,timing_waiting:0,timing_request:0};this.getParams=function(){if(performance&&"object"==typeof performance&&performance.timing){var b=this;this.params={navigation_type:performance.navigation.type?performance.navigation.type:255,timing_full_response:performance.timing.responseEnd-performance.timing.navigationStart,timing_dns:performance.timing.domainLookupEnd-performance.timing.domainLookupStart,
timing_download:performance.timing.responseEnd-performance.timing.responseStart,timing_waiting:performance.timing.responseStart-performance.timing.requestStart,timing_request:performance.timing.requestStart-performance.timing.connectEnd,fcp_start:0};performance.getEntriesByType("paint").find(function(c){"first-contentful-paint"===c.name&&(b.params.fcp_start=Math.floor(c.startTime))})}return this.params}}
function Events(){this.request={idsite:"",url:"",_id:"",_idts:"",localtime:Math.round((new Date).getTime()/1E3),h_id:hit_id,r:"",events:[]};this.setRequestVar=function(b,c){if("events"==b)return console.log("[Events] Variable Events reserved"),!1;this.request[b]=c;return!0};this.addEvent=function(b,c){if(!b)return console.log("[Events] The event is not added, name empty!"),!1;if("object"!=typeof c)return console.log("[Events] The event is not added, params must be an object!"),!1;c.etype=b;this.request.events.push(c);
return!0};this.getReguest=function(){this.request.r=String(Math.random()).slice(2,8);var b=JSON.parse(JSON.stringify(this.request));this.request.events=[];return b}}
function EventClick(b){var c=(new Meta).getMeta();this.ObserverTitleVer=function(c,g,d){b.addEvent("click",{ectgry:"title_ver",elabel:"article_id"in d?d.article_id:"",srcaid:"main",vstr:"hash"in d?d.hash:"",v2str:"algorithm"in d?d.algorithm:""})};this.ObserverRecommendAlg=function(c,g,d){b.addEvent("click",{ectgry:"recommend",elabel:"article_id"in d?d.article_id:"",srcaid:"source_aid"in d?d.source_aid:"",vstr:"underpage",v2str:"algorithm"in d?d.algorithm:""})};this.ObserverMainRecommendAlg=function(c,
g,d){b.addEvent("click",{ectgry:"recommend",elabel:"article_id"in d?d.article_id:"",vstr:"mainpage",v2str:"algorithm"in d?d.algorithm:""})};this.titleVerClick=function(){c&&"title_ver"in c&&b.addEvent("click",{ectgry:"ab_title",elabel:"article_id"in c?c.article_id:"",vstr:"title_ver"in c?c.title_ver:"",v2str:"title_alg"in c?c.title_alg:""})};this.recommendAlg=function(){c&&"rcmd_alg"in c&&b.addEvent("click",{ectgry:"recommend",elabel:"article_id"in c?c.article_id:"",vstr:"",v2str:"rcmd_alg"in c?c.rcmd_alg:
""})}}
function EventScroll(b){(new Meta).getMeta();var c=null;this.ObserverABTitle=function(c,g,d){b.addEvent("scroll",{ectgry:"ab_title",elabel:"article_id"in d?d.article_id:"",srcaid:"main",vstr:"hash"in d?d.hash:"",v2str:"algorithm"in d?d.algorithm:""})};this.ObserverInfinity=function(m,g,d){var f=1E3*parseInt(.041*("textlength"in d?d.textlength:100)+5),v={ectgry:"recommend",elabel:"article_id"in d?d.article_id:"",srcaid:"source_aid"in d?d.source_aid:"",vstr:"infinityscroll",v2str:"algorithm"in d?d.algorithm:
"",vuint64:"textlength"in d?d.textlength:""};(new Promise(function(d,g){c||clearTimeout(c);c=setTimeout(function(){b.addEvent("read",v);d()},f)})).then().catch(function(b){console.error("Event model error: "+b)});return!0};this.ObserverRcmdUnderArticle=function(c,g,d){b.addEvent("doscroll",{ectgry:"recommend",srcaid:"article_id"in d?d.article_id:"",vstr:"underpage",v2str:"algorithm"in d?d.algorithm:"",vlui64:"article_block_ids"in d?d.article_block_ids:[]})};this.ObserverArticleEnd=function(c,g,d){b.addEvent("scroll",
{ectgry:"recommend",elabel:"article_id"in d?d.article_id:"",vstr:"article_end",vuint64:"textlength"in d?d.textlength:""})}}function Tools(){this.serialize=function(b,c){var m=[],g;for(g in b)if(b.hasOwnProperty(g)){var d=c?c+"["+g+"]":g,f=b[g];m.push("object"==typeof f?this.serialize(f,d):d+"="+f)}return m.join("&")};this.hashchangeHandler=function(){var b=window.location.hash;b&&(b=b.split("#"),b[1]&&"analytics"==b[1]&&objScroll.visualization())}}
function Ping(){this.timeoutActivityStage=60;this.lastActivity=Math.floor(new Date/1E3);this.activityStage=1;this.getCurrentNum=function(){var b=Math.floor(new Date/1E3);b-this.lastActivity>this.timeoutActivityStage&&255>this.activityStage&&this.activityStage++;this.lastActivity=b;return this.activityStage}}
function Meta(){document.querySelectorAll(".ab__testing-info");this.getMeta=function(){var b=[],c=document.getElementsByTagName("meta"),m;for(m in c){var g=c[m];"object"==typeof g&&"getAttribute"in g&&g.getAttribute("name")&&-1<g.getAttribute("name").indexOf("analytics:")&&(b[g.getAttribute("name").split(":")[1]]=g.getAttribute("content"));"object"==typeof g&&"getAttribute"in g&&g.getAttribute("property")&&-1<g.getAttribute("property").indexOf("analytics:")&&(b[g.getAttribute("property").split(":")[1]]=
g.getAttribute("content"))}return b}}
function measureLoadPage(){this.get=function(b){var c={sum:{}},m=["img","css","script"],g=window.location.hostname;b=b?b:new RegExp("cdn(\\d+).img."+g);if(void 0!=window.performance.getEntries){g=window.performance.getEntries();for(i=0;i<g.length;i+=1){var d=g[i],f="name"in d?d.name:"",v="initiatorType"in d?d.initiatorType:"",z=this._getSize(d),d="duration"in d?d.duration:0;f.match(b)&&(f=m.indexOf(v),0<=f&&(f=m[f],f in c||(c[f]=[]),f in c.sum||(c.sum[f]={size:0,duration:0,count:0}),0<d&&(c[f].push({size:z,
duration:d}),c.sum[f].size+=z,c.sum[f].duration+=Math.floor(d),c.sum[f].count+=1)))}return c}};this._getSize=function(b){var c=0;"decodedBodySize"in b&&0<b.decodedBodySize?c=b.decodedBodySize:"encodedBodySize"in b&&0<b.encodedBodySize?c=b.encodedBodySize:"transferSize"in b&&0<b.transferSize&&(c=b.transferSize);return c}}
function EventModel(){this._subscribers={};this._events=[];this.push=function(b){if(3==b.length){var c=this;this._events.push(b);(new Promise(function(b,g){setTimeout(function(){!0===c._notify()?b():g()},0)})).then().catch(function(b){console.error("Event model error: "+b)});return!0}console.error("Event model: length array size is not 3");return!1};this.import=function(b){b&&(this._events=this._events.concat(b),this._notify());return!0};this.subscribe=function(b,c,m){b in this._subscribers||(this._subscribers[b]=
{});c in this._subscribers[b]||(this._subscribers[b][c]=[]);this._subscribers[b][c].push(m);return!0};this.unsubscribe=function(b,c){delete this._subscribers[b][c]};this._notify=function(){for(var b=this._events.length,c=0;c<b;c++){var m=this._events.shift();if(3==m.length){var g=[],d=m[0],f=m[1],m=m[2];if(d in this._subscribers&&(f in this._subscribers[d]||"*"in this._subscribers[d])){f in this._subscribers[d]&&(g=this._subscribers[d][f]);"*"in this._subscribers[d]&&(g=g.concat(this._subscribers[d]["*"]));
for(var v=0;v<g.length;v++)if(g[v])g[v](d,f,m)}}else console.error("Event model: length array size is not 3")}return!0}}function pwConfig(){this._config={};this.get=function(b){return b?b in this._config?this._config[b]:!1:this._config};this.set=function(b,c){this._config[b]=c}}"object"!==typeof JSON2&&(JSON2={});
(function(){function b(b){return 10>b?"0"+b:b}function c(b){d.lastIndex=0;return d.test(b)?'"'+b.replace(d,function(b){var c=z[b];return"string"===typeof c?c:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function m(d,g){var t,U,w,z,M=f,N,r=g[d];r&&"object"===typeof r&&(t=r,w=Object.prototype.toString.apply(t),r="[object Date]"===w?isFinite(t.valueOf())?t.getUTCFullYear()+"-"+b(t.getUTCMonth()+1)+"-"+b(t.getUTCDate())+"T"+b(t.getUTCHours())+":"+b(t.getUTCMinutes())+":"+b(t.getUTCSeconds())+
"Z":null:"[object String]"===w||"[object Number]"===w||"[object Boolean]"===w?t.valueOf():"[object Array]"!==w&&"function"===typeof t.toJSON?t.toJSON(d):t);"function"===typeof I&&(r=I.call(g,d,r));switch(typeof r){case "string":return c(r);case "number":return isFinite(r)?String(r):"null";case "boolean":case "null":return String(r);case "object":if(!r)return"null";f+=v;N=[];if("[object Array]"===Object.prototype.toString.apply(r)){z=r.length;for(t=0;t<z;t+=1)N[t]=m(t,r)||"null";w=0===N.length?"[]":
f?"[\n"+f+N.join(",\n"+f)+"\n"+M+"]":"["+N.join(",")+"]";f=M;return w}if(I&&"object"===typeof I)for(z=I.length,t=0;t<z;t+=1)"string"===typeof I[t]&&(U=I[t],(w=m(U,r))&&N.push(c(U)+(f?": ":":")+w));else for(U in r)Object.prototype.hasOwnProperty.call(r,U)&&(w=m(U,r))&&N.push(c(U)+(f?": ":":")+w);w=0===N.length?"{}":f?"{\n"+f+N.join(",\n"+f)+"\n"+M+"}":"{"+N.join(",")+"}";f=M;return w}}var g=/[\x00\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d=/[\\\"\x00-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
f,v,z={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},I;"function"!==typeof JSON2.stringify&&(JSON2.stringify=function(b,c,d){var g;v=f="";if("number"===typeof d)for(g=0;g<d;g+=1)v+=" ";else"string"===typeof d&&(v=d);if((I=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON2.stringify");return m("",{"":b})});"function"!==typeof JSON2.parse&&(JSON2.parse=function(b,c){function d(b,f){var g,m,r=b[f];if(r&&"object"===typeof r)for(g in r)Object.prototype.hasOwnProperty.call(r,
g)&&(m=d(r,g),void 0!==m?r[g]=m:delete r[g]);return c.call(b,f,r)}var f;b=String(b);g.lastIndex=0;g.test(b)&&(b=b.replace(g,function(b){return"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(b.replace(/\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return f=eval("("+b+")"),"function"===typeof c?d({"":f},""):f;throw new SyntaxError("JSON2.parse");})})();
"object"!==typeof _paq&&(_paq=[]);
"object"!==typeof Piwik&&(Piwik=function(){function b(a){return"undefined"!==typeof a}function c(a){return"function"===typeof a}function m(a){return"object"===typeof a}function g(a){return"string"===typeof a||a instanceof String}function d(){var a,e,b;for(a=0;a<arguments.length;a+=1)b=arguments[a],e=b.shift(),g(e)?H[e].apply(H,b):e.apply(H,b)}function f(a,e,b,p){if(a.addEventListener)return a.addEventListener(e,b,p),!0;if(a.attachEvent)return a.attachEvent("on"+e,b);a["on"+e]=b}function v(a,e){var b=
"",p,d;for(p in ka)Object.prototype.hasOwnProperty.call(ka,p)&&(d=ka[p][a],c(d)&&(b+=d(e)));return b}function z(){var a;if(!la)for(la=!0,v("load"),a=0;a<La.length;a++)La[a]();return!0}function I(a,e){var b=q.createElement("script");b.type="text/javascript";b.src=a;b.readyState?b.onreadystatechange=function(){var a=this.readyState;if("loaded"===a||"complete"===a)b.onreadystatechange=null,e()}:b.onload=e;q.getElementsByTagName("head")[0].appendChild(b)}function wa(){var a="";try{a=l.top.document.referrer}catch(b){if(l.parent)try{a=
l.parent.document.referrer}catch(c){a=""}}""===a&&(a=q.referrer);return a}function jb(a){return(a=/^([a-z]+):/.exec(a))?a[1]:null}function t(a){var b=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(a);return b?b[1]:a}function U(a,b){var c=(new RegExp("[\\?&#]"+b+"=([^&#]*)")).exec(a);return c?kb(c[1]):""}function w(a){var b=function(a,b){return a<<b|a>>>32-b},c=function(a){var b="",e,d;for(e=7;0<=e;e--)d=a>>>4*e&15,b+=d.toString(16);return b},p,d,g=[],f=1732584193,q=4023233417,k=2562383102,l=271733878,
m=3285377520,u,t,n,r,v,w=[];a=lb(x(a));u=a.length;for(p=0;p<u-3;p+=4)d=a.charCodeAt(p)<<24|a.charCodeAt(p+1)<<16|a.charCodeAt(p+2)<<8|a.charCodeAt(p+3),w.push(d);switch(u&3){case 0:p=2147483648;break;case 1:p=a.charCodeAt(u-1)<<24|8388608;break;case 2:p=a.charCodeAt(u-2)<<24|a.charCodeAt(u-1)<<16|32768;break;case 3:p=a.charCodeAt(u-3)<<24|a.charCodeAt(u-2)<<16|a.charCodeAt(u-1)<<8|128}for(w.push(p);14!==(w.length&15);)w.push(0);w.push(u>>>29);w.push(u<<3&4294967295);for(a=0;a<w.length;a+=16){for(p=
0;16>p;p++)g[p]=w[a+p];for(p=16;79>=p;p++)g[p]=b(g[p-3]^g[p-8]^g[p-14]^g[p-16],1);d=f;u=q;t=k;n=l;r=m;for(p=0;19>=p;p++)v=b(d,5)+(u&t|~u&n)+r+g[p]+1518500249&4294967295,r=n,n=t,t=b(u,30),u=d,d=v;for(p=20;39>=p;p++)v=b(d,5)+(u^t^n)+r+g[p]+1859775393&4294967295,r=n,n=t,t=b(u,30),u=d,d=v;for(p=40;59>=p;p++)v=b(d,5)+(u&t|u&n|t&n)+r+g[p]+2400959708&4294967295,r=n,n=t,t=b(u,30),u=d,d=v;for(p=60;79>=p;p++)v=b(d,5)+(u^t^n)+r+g[p]+3395469782&4294967295,r=n,n=t,t=b(u,30),u=d,d=v;f=f+d&4294967295;q=q+u&4294967295;
k=k+t&4294967295;l=l+n&4294967295;m=m+r&4294967295}v=c(f)+c(q)+c(k)+c(l)+c(m);return v.toLowerCase()}function $b(a,b,d){if("translate.googleusercontent.com"===a)""===d&&(d=b),b=U(b,"u"),a=t(b);else if("cc.bingj.com"===a||"webcache.googleusercontent.com"===a||"74.6."===a.slice(0,5))b=q.links[0].href,a=t(b);return[a,b,d]}function M(a){var b=a.length;"."===a.charAt(--b)&&(a=a.slice(0,b));"*."===a.slice(0,2)&&(a=a.slice(1));return a}function N(a){a=a&&a.text?a.text:a;if(!g(a)){var e=q.getElementsByTagName("title");
e&&b(e[0])&&(a=e[0].text)}return a}function r(a){return a?!b(a.children)&&b(a.childNodes)||b(a.children)?a.children:[]:[]}function ba(a,e){if(a&&a.indexOf)return a.indexOf(e);if(!b(a)||null===a||!a.length)return-1;var d=a.length;if(0===d)return-1;for(var c=0;c<d;){if(a[c]===e)return c;c++}return-1}function mb(a){function e(a,b){if(l.getComputedStyle)return q.defaultView.getComputedStyle(a,null)[b];if(a.currentStyle)return a.currentStyle[b]}function d(c,g,f,k,l,m,t){var n=c.parentNode,r;a:{for(r=c.parentNode;r;){if(r===
q){r=!0;break a}r=r.parentNode}r=!1}if(!r)return!1;if(9===n.nodeType)return!0;if("0"===e(c,"opacity")||"none"===e(c,"display")||"hidden"===e(c,"visibility"))return!1;b(g)&&b(f)&&b(k)&&b(l)&&b(m)&&b(t)||(g=c.offsetTop,l=c.offsetLeft,k=g+c.offsetHeight,f=l+c.offsetWidth,m=c.offsetWidth,t=c.offsetHeight);if(a===c&&(0===t||0===m)&&"hidden"===e(c,"overflow"))return!1;if(n){if("hidden"===e(n,"overflow")||"scroll"===e(n,"overflow"))if(l+1>n.offsetWidth+n.scrollLeft||l+m-1<n.scrollLeft||g+1>n.offsetHeight+
n.scrollTop||g+t-1<n.scrollTop)return!1;c.offsetParent===n&&(l+=n.offsetLeft,g+=n.offsetTop);return d(n,g,f,k,l,m,t)}return!0}return a?d(a):!1}function Na(a,b){if(b)return b;"piwik.php"===a.slice(-9)&&(a=a.slice(0,a.length-9));return a}function ca(a){var b=/index\.php\?module=Overlay&action=startOverlaySession&idSite=([0-9]+)&period=([^&]+)&date=([^&]+)$/.exec(q.referrer);if(b){if(b[1]!==String(a))return!1;l.name="Piwik_Overlay###"+b[2]+"###"+b[3]}a=l.name.split("###");return 3===a.length&&"Piwik_Overlay"===
a[0]}function bc(a,b,c){var d=l.name.split("###"),g=d[1],f=d[2],k=Na(a,b);I(k+"plugins/Overlay/client/client.js?v=1",function(){Piwik_Overlay_Client.initialize(k,c,g,f)})}function na(a,e,d){function p(h,a,b,e,c,d){if(!Z){var g;b&&(g=new Date,g.setTime(g.getTime()+b));q.cookie=h+"="+x(a)+(b?";expires="+g.toGMTString():"")+";path="+(e||"/")+(c?";domain="+c:"")+(d?";secure":"")}}function r(h){return Z?0:(h=(new RegExp("(^|;)[ ]*"+h+"=([^;]*)")).exec(q.cookie))?kb(h[2]):0}function z(h){var a;return nb?
(a=/#.*/,h.replace(a,"")):h}function I(h){var a,b,e;for(a=0;a<za.length;a++){b=M(za[a].toLowerCase());if(h===b)return!0;if("."===b.slice(0,1)){if(h===b.slice(1))return!0;e=h.length-b.length;if(0<e&&h.slice(e)===b)return!0}}return!1}function H(h,a){var b=new Image(1,1);b.onload=function(){G=0;"function"===typeof a&&a()};b.src=T+(0>T.indexOf("?")?"?":"&")+h}function ba(h,a,b){var e=new Image(1,1);e.onload=function(){G=0;"function"===typeof b&&b()};e.src=a+(0>T.indexOf("?")?"?":"&")+h}function R(h,a,
oa){b(oa)&&null!==oa||(oa=!0);try{var e=l.XMLHttpRequest?new l.XMLHttpRequest:l.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;e.open("POST",T,!0);e.onreadystatechange=function(){4!==this.readyState||200<=this.status&&300>this.status||!oa?"function"===typeof a&&a():H(h,a)};e.setRequestHeader("Content-Type",ob);e.send(h)}catch(c){oa&&H(h,a)}}function xa(h){h=(new Date).getTime()+h;if(!pa||h>pa)pa=h}function u(h){var a=(new Date).getTime();da&&a<da?(a=da-a,setTimeout(h,a),xa(a+50),da+=50):
(!1===da&&(da=a+800),h())}function K(h,a,b){!Aa&&h&&u(function(){"POST"===pb?R(h,b):H(h,b);xa(a)})}function ya(h,a){var b;b=Aa?!1:h&&h.length;if(b){var e='{"requests":["?'+h.join('","?')+'"]}';u(function(){R(e,null,!1);xa(a)})}}function S(h){return qb+h+"."+Q+"."+rb}function va(){if(Z)return"0";if(!b(F.cookieEnabled)){var h=S("testcookie");p(h,"1");return"1"===r(h)?"1":"0"}return F.cookieEnabled?"1":"0"}function fa(){rb=sb((W||Pa)+(X||"/")).slice(0,4)}function Ma(){var h=S("cvar"),h=r(h);return h.length&&
(h=JSON2.parse(h),m(h))?h:{}}function A(){Qa=(new Date).getTime()}function C(){Ra=!0}function ma(){var h=new Date,a=Math.round(h.getTime()/1E3),b=r(S("id"));b?(h=b.split("."),h.unshift("0")):(Sa||(Sa=sb((F.userAgent||"")+(F.platform||"")+JSON2.stringify(Y)+h.getTime()+Math.random()).slice(0,16)),h=["1",Sa,a,0,a,"",""]);return h}function na(){var h=(new Date).getTime(),a=ma();return 1E3*parseInt(a[2],10)+Ta-h}function Na(h,a,b,e,c,d){var g=na();p(S("id"),h+"."+a+"."+b+"."+e+"."+c+"."+d,g,X,W)}function ga(){var h=
r(S("ref"));if(h.length)try{if(h=JSON2.parse(h),m(h))return h}catch(a){}return["","",0,""]}function tb(){var h=Z;Z=!1;p(S("id"),"",-86400,X,W);p(S("ses"),"",-86400,X,W);p(S("cvar"),"",-86400,X,W);p(S("ref"),"",-86400,X,W);Z=h}function ub(h){if(h&&m(h)){var a=[],b;for(b in h)Object.prototype.hasOwnProperty.call(h,b)&&a.push(b);b={};a.sort();var e=a.length,c;for(c=0;c<e;c++)b[a[c]]=h[a[c]];return b}}function D(h,a,e,d){function g(h,a){var b=JSON2.stringify(h);return 2<b.length?"&"+a+"="+x(b):""}var f,
P=new Date,l=Math.round(P.getTime()/1E3),k,m,n,w,u,B,y,F,A,C,G=O,J=S("ses"),L=S("ref"),N=S("cvar");y=ma();C=r(J);A=ga();var K=qa||Ua,D,H;Z&&tb();if(Aa)return"";k=y[0];m=y[1];w=y[2];n=y[3];u=y[4];B=y[5];b(y[6])||(y[6]="");y=y[6];b(d)||(d="");var M=q.characterSet||q.charset;M&&"utf-8"!==M.toLowerCase()||(M=null);D=A[0];H=A[1];F=A[2];A=A[3];var V;if(C)V=JSON2.parse(C);else{C=Ba/1E3;if(!B||l-B>C)n++,B=u;if(!Va||!D.length){for(f in Ca)if(Object.prototype.hasOwnProperty.call(Ca,f)&&(D=U(K,Ca[f]),D.length))break;
for(f in Da)if(Object.prototype.hasOwnProperty.call(Da,f)&&(H=U(K,Da[f]),H.length))break}u=t(ha);C=A.length?t(A):"";!u.length||I(u)||Va&&C.length&&!I(C)||(A=ha);if(A.length||D.length)F=l,A=[D,H,F,z(A.slice(0,1024))],p(L,JSON2.stringify(A),vb,X,W);h+="&new_session=1"}P.getMonth();u=objPerformance.getParams();L=(new measureLoadPage).get(wb);objPWConfig.set("site_id",Q);objPWConfig.set("tracker_url",T);objPWConfig.set("visitor_id",m);h+="&idsite="+Q+"&rec=1&r="+String(Math.random()).slice(2,8)+"&ltime="+
Math.round(P.getTime()/1E3)+"&url="+x(z(K))+(ha.length?"&urlref="+x(z(ha).substr(0,1E3)):"")+(Ea.length?"&uid="+x(Ea):"")+"&_id="+m+"&_idts="+w+"&_idvc="+n+"&_idn="+k+(D.length?"&_rcn="+x(D):"")+(H.length?"&_rck="+x(H):"")+"&_refts="+F+"&_viewts="+B+(String(y).length?"&_ects="+y:"")+(M?"&cs="+x(M):"")+"&s_img=0&mdata="+xb+"&n_tp="+u.navigation_type+"&t_fl_r="+u.timing_full_response+"&t_dns="+u.timing_dns+"&t_dw="+u.timing_download+"&t_wt="+u.timing_waiting+"&t_rq="+u.timing_request+"&fcp_start="+
u.fcp_start+"&ver="+_version+"&h_id="+hit_id+"&l_arc="+objScroll.longArticle();if((P=(new Meta).getMeta())&&"object"==typeof P)var R=objTools.serialize(P,"meta");R&&(h+="&"+R);for(f in Y)Object.prototype.hasOwnProperty.call(Y,f)&&(h+="&"+f+"="+Y[f]);a?h+="&data="+x(JSON2.stringify(a)):aa&&(h+="&data="+x(JSON2.stringify(aa)));"sum"in L&&("css"in L.sum&&(h+="&rspf[css][size]="+L.sum.css.size,h+="&rspf[css][count]="+L.sum.css.count,h+="&rspf[css][dur]="+L.sum.css.duration),"script"in L.sum&&(h+="&rspf[script][size]="+
L.sum.script.size,h+="&rspf[script][count]="+L.sum.script.count,h+="&rspf[script][dur]="+L.sum.script.duration),"img"in L.sum&&(h+="&rspf[img][size]="+L.sum.img.size,h+="&rspf[img][count]="+L.sum.img.count,h+="&rspf[img][dur]="+L.sum.img.duration),h+="&rspf[marker]="+yb);a=ub(ea);R=ub(Wa);h+=g(a,"cvar");h+=g(R,"e_cvar");if(O){h+=g(O,"_cvar");for(f in G)Object.prototype.hasOwnProperty.call(G,f)&&(""!==O[f][0]&&""!==O[f][1]||delete O[f]);zb&&p(N,JSON2.stringify(O),Ba,X,W)}Ab&&(Xa?h+="&gt_ms="+Xa:ia&&
ia.timing&&ia.timing.requestStart&&ia.timing.responseEnd&&(h+="&gt_ms="+(ia.timing.responseEnd-ia.timing.requestStart)));f=dc(V);G={depth:f};Na(m,w,n,l,B,b(d)&&String(d).length?d:y);p(J,JSON2.stringify(G),Ba,X,W);h=h+("&depth="+f)+v(e);Ya.length&&(h+="&"+Ya);c(Za)&&(h=Za(h));return h}function dc(h){var a=0;h&&(a=h.depth);h=t(ha);var b=t(location.hostname);return h&&h==b?a+1:a}function Bb(a,E,e,c,d,g){var f="idgoal=0",p,P=new Date,l=[],k;String(a).length&&(f+="&ec_id="+x(a),p=Math.round(P.getTime()/
1E3));f+="&revenue="+E;String(e).length&&(f+="&ec_st="+e);String(c).length&&(f+="&ec_tx="+c);String(d).length&&(f+="&ec_sh="+d);String(g).length&&(f+="&ec_dt="+g);if(y){for(k in y)Object.prototype.hasOwnProperty.call(y,k)&&(b(y[k][1])||(y[k][1]=""),b(y[k][2])||(y[k][2]=""),b(y[k][3])&&0!==String(y[k][3]).length||(y[k][3]=0),b(y[k][4])&&0!==String(y[k][4]).length||(y[k][4]=1),l.push(y[k]));f+="&ec_items="+x(JSON2.stringify(l))}f=D(f,aa,"ecommerce",p);K(f,B)}function ec(a,b){var e=new Date,c=a||Cb,
c=c.substr(0,500),c=D("action_name="+x(N(c)),b,"log");K(c,B);$a&&ra&&!Db&&(Db=!0,f(q,"click",A),f(q,"mouseup",A),f(q,"mousedown",A),f(q,"mousemove",A),f(q,"mousewheel",A),f(l,"DOMMouseScroll",A),f(l,"scroll",A),f(q,"keypress",A),f(q,"keydown",A),f(q,"keyup",A),f(l,"resize",A),f(l,"focus",A),f(l,"blur",A),Qa=e.getTime(),setTimeout(function cc(){var a;e=new Date;Qa+ra>e.getTime()&&($a<e.getTime()&&(a=D("ping=1",b,"ping"),K(a,B)),setTimeout(cc,ra))},ra))}function ab(a,b){var e,c="(^| )(piwik[_-]"+b;
if(a)for(e=0;e<a.length;e++)c+="|"+a[e];return new RegExp(c+")( |$)")}function sa(a){return T&&a&&0===String(a).indexOf(T)}function bb(a){var E=a;for(a=E.parentNode;null!==a&&b(a)&&!k.isLinkElement(E);)E=a,a=E.parentNode;a=E;if(k.hasNodeAttribute(a,"href")&&b(a.href)&&(E=k.getAttributeValueFromNode(a,"href"),!sa(E))){var E=a.hostname||t(a.href),e=E.toLowerCase(),E=a.href.replace(E,e);if(!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto):/i.test(E)){a=a.className;e=I(e);if(sa(E))a=
0;else{var c=ab(Eb,"download"),d=ab(Fb,"link"),f=new RegExp("\\.("+ta+")([?&#]|$)","i");a=d.test(a)?"link":c.test(a)||f.test(E)?"download":e?0:"link"}if(a)return{type:a,href:E}}}}function ua(a,b,e,c){if(a=n.buildInteractionRequestParams(a,b,e,c))return D(a,null,"contentInteraction")}function Gb(a,E,e,c,d){if(b(a)){if(sa(a))return a;var f=n.toAbsoluteUrl(a),f="redirecturl="+x(f)+"&",f=f+ua(E,e,c,d||a);a="&";0>T.indexOf("?")&&(a="?");return T+a+f}}function cb(a,b){if(!a||!b)return!1;var e=n.findTargetNode(a);
if(n.shouldIgnoreInteraction(e))return!1;var e=n.findTargetNodeNoDefault(a),c;if(c=e)c=!(e&&b&&(e.contains?e.contains(b):e===b||e.compareDocumentPosition&&e.compareDocumentPosition(b)&16));return c?!1:!0}function Hb(a,b,e){if(a){var c=n.findParentContentNode(a);if(c&&cb(c,a)&&(a=n.buildContentBlock(c)))return!a.target&&e&&(a.target=e),n.buildInteractionRequestParams(b,a.name,a.piece,a.target)}}function Ib(a){if(!V||!V.length)return!1;var b,e;for(b=0;b<V.length;b++)if((e=V[b])&&e.name===a.name&&e.piece===
a.piece&&e.target===a.target)return!0;return!1}function db(a){if(!a)return!1;var b=n.findTargetNode(a);if(!b||n.shouldIgnoreInteraction(b))return!1;var e=bb(b);if(eb&&e&&e.type)return!1;if(k.isLinkElement(b)&&k.hasNodeAttributeWithValue(b,"href")){e=String(k.getAttributeValueFromNode(b,"href"));if(0===e.indexOf("#"))return!1;if(sa(e))return!0;if(!n.isUrlToCurrentDomain(e))return!1;var c=n.buildContentBlock(a);if(!c)return;a=c.name;var d=c.piece,c=c.target;if(!k.hasNodeAttributeWithValue(b,n.CONTENT_TARGET_ATTR)||
b.wasContentTargetAttrReplaced)b.wasContentTargetAttrReplaced=!0,c=n.toAbsoluteUrl(e),k.setAnyAttribute(b,n.CONTENT_TARGET_ATTR,c);e=Gb(e,"click",a,d,c);n.setHrefAttribute(b,e);return!0}return!1}function Jb(a){return function(b){if(a){var e=n.findParentContentNode(a),c;b&&(c=b.target||b.srcElement);c||(c=a);if(cb(e,c)){xa(B);k.isLinkElement(a)&&k.hasNodeAttributeWithValue(a,"href")&&k.hasNodeAttributeWithValue(a,n.CONTENT_TARGET_ATTR)&&(b=k.getAttributeValueFromNode(a,"href"),!sa(b)&&a.wasContentTargetAttrReplaced&&
k.setAnyAttribute(a,n.CONTENT_TARGET_ATTR,""));b=bb(a);if(Fa&&b&&b.type)return b.type;if(db(e))return"href";if(e=n.buildContentBlock(e))return e=ua("click",e.name,e.piece,e.target),K(e,B),e}}}}function Kb(a){if(a&&a.length){var b,e;for(b=0;b<a.length;b++)(e=n.findTargetNode(a[b]))&&!e.contentInteractionTrackingSetupDone&&(e.contentInteractionTrackingSetupDone=!0,f(e,"click",Jb(e)))}}function Lb(a,b){if(!a||!a.length)return[];var e,c;for(e=0;e<a.length;e++)Ib(a[e])?(a.splice(e,1),e--):V.push(a[e]);
if(!a||!a.length)return[];if(b&&b.length)for(e=0;e<b.length;e++)db(b[e]);Kb(b);var d=[];for(e=0;e<a.length;e++)c=D(n.buildImpressionRequestParams(a[e].name,a[e].piece,a[e].target),void 0,"contentImpressions"),d.push(c);return d}function Ga(a){var b=n.collectContent(a);return Lb(b,a)}function fb(a){if(!a||!a.length)return[];var b;for(b=0;b<a.length;b++)n.isNodeVisible(a[b])||(a.splice(b,1),b--);return a&&a.length?Ga(a):[]}function Mb(a,b,e){a=n.buildImpressionRequestParams(a,b,e);return D(a,null,"contentImpression")}
function Nb(a,b){if(a){var e=n.findParentContentNode(a);if(e=n.buildContentBlock(e))return b||(b="Unknown"),ua(b,e.name,e.piece,e.target)}}function Ob(a,e,c,d,f){if(0===String(a).length||0===String(e).length)return!1;a="e_c="+x(a)+"&e_a="+x(e)+(b(c)?"&e_n="+x(c):"")+(b(d)?"&e_v="+x(d):"");f=D(a,f,"event");K(f,B)}function Pb(a,b,e,c,d){b=b+"="+x(z(a));(a=Hb(d,"click",a))&&(b+="&"+a);e=D(b,e,"link");K(e,c?0:B,c)}function Qb(a,b){return""!==a?a+b.charAt(0).toUpperCase()+b.slice(1):b}function J(a){var b,
e,c=["","webkit","ms","moz"],d;if(!Rb)for(e=0;e<c.length;e++)if(d=c[e],Object.prototype.hasOwnProperty.call(q,Qb(d,"hidden"))){"prerender"===q[Qb(d,"visibilityState")]&&(b=!0);break}b?f(q,d+"visibilitychange",function Oa(){q.removeEventListener(d+"visibilitychange",Oa,!1);a()}):a()}function Ha(a){"complete"===q.readyState?a():l.addEventListener?l.addEventListener("load",a):l.attachEvent&&l.attachEvent("onLoad",a)}function gb(a){var b=!1;(b=q.attachEvent?"complete"===q.readyState:"loading"!==q.readyState)?
a():q.addEventListener?q.addEventListener("DOMContentLoaded",a):q.attachEvent&&q.attachEvent("onreadystatechange",a)}function Sb(a){var b=bb(a);b&&b.type&&(b.href=lb(b.href),Pb(b.href,b.type,void 0,null,a))}function hb(a){var b,e;a=a||l.event;b=a.which||a.button;e=a.target||a.srcElement;"click"===a.type?e&&Sb(e):"mousedown"===a.type?1!==b&&2!==b||!e?Ia=Ja=null:(Ia=b,Ja=e):"mouseup"===a.type&&(b===Ia&&e===Ja&&Sb(e),Ia=Ja=null)}function Tb(a,b){b?(f(a,"mouseup",hb,!1),f(a,"mousedown",hb,!1)):f(a,"click",
hb,!1)}function Ub(a){if(!Fa){Fa=!0;var b,e=ab(Vb,"ignore"),c=q.links;if(c)for(b=0;b<c.length;b++)e.test(c[b].className)||Tb(c[b],a)}}function Wb(a,b,e){function c(){d=!0}if(ja)return!0;ja=!0;var d=!1,f,g;Ha(function(){function p(a){setTimeout(function(){ja&&(d=!1,e.trackVisibleContentImpressions(),p(a))},a)}function P(a){setTimeout(function(){ja&&(d&&(d=!1,e.trackVisibleContentImpressions()),P(a))},a)}if(a){f=["scroll","resize"];for(g=0;g<f.length;g++)q.addEventListener?q.addEventListener(f[g],c):
l.attachEvent("on"+f[g],c);P(100)}b&&0<b&&(b=parseInt(b,10),p(b))})}var Ka={},ib=$b(q.domain,l.location.href,wa()),Pa=M(ib[0]),Ua=ib[1],ha=ib[2],Xb=!1,pb="GET",ob="application/x-www-form-urlencoded; charset=UTF-8",T=a||"//a.ria.ru/counter",Yb="",Ya="",Q=e||"",xb="",yb="",wb=null,Ea="",qa,Cb=q.title,ta="7z|aac|apk|ar[cj]|as[fx]|avi|azw3|bin|csv|deb|dmg|docx?|epub|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mobi|mp(2|3|4|e?g)|mov(ie)?|ms[ip]|od[bfgpst]|og[gv]|pdf|phps|png|pptx?|qtm?|ra[mr]?|rpm|sea|sit|tar|t?bz2?|tgz|torrent|txt|wav|wm[av]|wpd||xlsx?|xml|z|zip",
za=[Pa],Vb=[],Eb=[],Fb=[],B=500,$a,ra,nb,aa,Ca=["pk_campaign","piwik_campaign","utm_campaign","utm_source","utm_medium"],Da=["pk_kwd","piwik_kwd","utm_term"],qb="_pk_",W,X,Z=!1,Aa,Rb,Va,Ta=339552E5,Ba=18E5,vb=15768E6,Ab=!0,Xa=0,zb=!1,O=!1,Za,ea={},Wa={},y={},Y={},V=[],ja=!1,da=!1,Fa=!1,eb=!1,Db=!1,Qa,Ra=!1,Ia,Ja,sb=w,rb,Sa=d;(function(){var a,e,d={pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",
java:"application/x-java-vm",gears:"application/x-googlegears",ag:"application/x-silverlight"},f=/Mac OS X.*Safari\//.test(F.userAgent)?l.devicePixelRatio||1:1;if(!/MSIE/.test(F.userAgent)){if(F.mimeTypes&&F.mimeTypes.length)for(a in d)Object.prototype.hasOwnProperty.call(d,a)&&(e=F.mimeTypes[d[a]],Y[a]=e&&e.enabledPlugin?"1":"0");"unknown"!==typeof navigator.javaEnabled&&b(F.javaEnabled)&&F.javaEnabled()&&(Y.java="1");c(l.GearsFactory)&&(Y.gears="1");Y.cookie=va()}Y.res=Zb.width*f+"x"+Zb.height*
f})();fa();v("run",function(a,e){var c=null;if(g(a)&&!b(Ka[a])&&e){if(m(e))c=e;else if(g(e))try{eval("hookObj ="+e)}catch(d){}Ka[a]=c}return c});return{hook:Ka,getHook:function(a){return Ka[a]},getQuery:function(){return k},getContent:function(){return n},buildContentImpressionRequest:Mb,buildContentInteractionRequest:ua,buildContentInteractionRequestNode:Nb,buildContentInteractionTrackingRedirectUrl:Gb,getContentImpressionsRequestsFromNodes:Ga,getCurrentlyVisibleContentImpressionsRequestsIfNotTrackedYet:fb,
trackCallbackOnLoad:Ha,trackCallbackOnReady:gb,buildContentImpressionsRequests:Lb,wasContentImpressionAlreadyTracked:Ib,appendContentInteractionToRequestIfPossible:Hb,setupInteractionsTracking:Kb,trackContentImpressionClickInteraction:Jb,internalIsNodeVisible:mb,isNodeAuthorizedToTriggerInteraction:cb,replaceHrefIfInternalLink:db,getConfigDownloadExtensions:function(){return ta},enableTrackOnlyVisibleContent:function(a,b){return Wb(a,b,this)},clearTrackedContentImpressions:function(){V=[]},getTrackedContentImpressions:function(){return V},
getTrackerUrl:function(){return T},clearEnableTrackOnlyVisibleContent:function(){ja=!1},disableLinkTracking:function(){eb=Fa=!1},getConfigVisitorCookieTimeout:function(){return Ta},getRemainingVisitorCookieTimeout:na,getVisitorId:function(){return ma()[1]},getVisitorInfo:function(){return ma()},getAttributionInfo:function(){return ga()},getAttributionCampaignName:function(){return ga()[0]},getAttributionCampaignKeyword:function(){return ga()[1]},getAttributionReferrerTimestamp:function(){return ga()[2]},
getAttributionReferrerUrl:function(){return ga()[3]},setTrackerUrl:function(a){T=a},setSiteId:function(a){Q=a},setMetadata:function(a){xb=a},setResperfMarker:function(a){yb=a},setCDNMask:function(a){wb=a},setUserId:function(a){Ea=a},getUserId:function(){return Ea},setCustomData:function(a,b){m(a)?aa=a:(aa||(aa={}),aa[a]=b)},getCustomData:function(){return aa},setCustomRequestProcessing:function(a){Za=a},appendToTrackingUrl:function(a){Ya=a},getRequest:function(a){return D(a)},addPlugin:function(a,
b){ka[a]=b},setCustomVariable:function(a,e,c,d){b(d)||(d="visit");b(e)&&(b(c)||(c=""),0<a&&(e=g(e)?e:String(e),c=g(c)?c:String(c),e=[e.slice(0,200),c.slice(0,200)],"visit"===d||2===d?(!1===O&&(O=Ma()),O[a]=e):"page"===d||3===d?ea[a]=e:"event"===d&&(Wa[a]=e)))},getCustomVariable:function(a,e){var c;b(e)||(e="visit");if("page"===e||3===e)c=ea[a];else if("event"===e)c=Wa[a];else if("visit"===e||2===e)!1===O&&(O=Ma()),c=O[a];return!b(c)||c&&""===c[0]?!1:c},deleteCustomVariable:function(a,b){this.getCustomVariable(a,
b)&&this.setCustomVariable(a,"","",b)},storeCustomVariablesInCookie:function(){zb=!0},setLinkTrackingTimer:function(a){B=a},setDownloadExtensions:function(a){ta=a},addDownloadExtensions:function(a){ta+="|"+a},setDomains:function(a){za=g(a)?[a]:a;za.push(Pa)},setIgnoreClasses:function(a){Vb=g(a)?[a]:a},setRequestMethod:function(a){pb=a||"GET"},setRequestContentType:function(a){ob=a||"application/x-www-form-urlencoded; charset=UTF-8"},setReferrerUrl:function(a){ha=a},setCustomUrl:function(a){var b=
Ua,e;jb(a)?qa=a:"/"===a.slice(0,1)?qa=jb(b)+"://"+t(b)+a:(b=z(b),e=b.indexOf("?"),0<=e&&(b=b.slice(0,e)),e=b.lastIndexOf("/"),e!==b.length-1&&(b=b.slice(0,e+1)),qa=b+a)},setDocumentTitle:function(a){Cb=a},setAPIUrl:function(a){Yb=a},setDownloadClasses:function(a){Eb=g(a)?[a]:a},setLinkClasses:function(a){Fb=g(a)?[a]:a},setCampaignNameKey:function(a){Ca=g(a)?[a]:a},setCampaignKeywordKey:function(a){Da=g(a)?[a]:a},discardHashTag:function(a){nb=a},setCookieNamePrefix:function(a){qb=a;O=Ma()},setCookieDomain:function(a){W=
M(a);fa()},setCookiePath:function(a){X=a;fa()},setVisitorCookieTimeout:function(a){Ta=1E3*a},setSessionCookieTimeout:function(a){Ba=1E3*a},setReferralCookieTimeout:function(a){vb=1E3*a},setConversionAttributionFirstReferrer:function(a){Va=a},disableCookies:function(){Z=!0;Y.cookie="0"},deleteCookies:function(){tb()},setDoNotTrack:function(a){var b=F.doNotTrack||F.msDoNotTrack;(Aa=a&&("yes"===b||"1"===b))&&this.disableCookies()},addListener:function(a,b){Tb(a,b)},enableLinkTracking:function(a){eb=
!0;la?Ub(a):La.push(function(){Ub(a)})},enableJSErrorTracking:function(){if(!Xb){Xb=!0;var a=l.onerror;l.onerror=function(b,e,c,d,f){J(function(){var a=e+":"+c;d&&(a+=":"+d);Ob("JavaScript Errors",a,b)});return a?a(b,e,c,d,f):!1}}},disablePerformanceTracking:function(){Ab=!1},setGenerationTimeMs:function(a){Xa=parseInt(a,10)},setHeartBeatTimer:function(a,b){$a=(new Date).getTime()+1E3*a;ra=1E3*b},killFrame:function(){l.location!==l.top.location&&(l.top.location=l.location)},redirectFile:function(a){"file:"===
l.location.protocol&&(l.location=a)},setCountPreRendered:function(a){Rb=a},trackGoal:function(a,b,e){J(function(){var c=D("idgoal="+a+(b?"&revenue="+b:""),e,"goal");K(c,B)})},trackLink:function(a,b,e,c){J(function(){Pb(a,b,e,c)})},trackPageView:function(a,b){V=[];ca(Q)?J(function(){bc(T,Yb,Q)}):J(function(){ec(a,b)})},trackAllContentImpressions:function(){ca(Q)||J(function(){gb(function(){var a=n.findContentNodes(),a=Ga(a);ya(a,B)})})},trackVisibleContentImpressions:function(a,e){ca(Q)||(b(a)||(a=
!0),b(e)||(e=750),Wb(a,e,this),J(function(){Ha(function(){var a=n.findContentNodes(),a=fb(a);ya(a,B)})}))},trackContentImpression:function(a,b,e){!ca(Q)&&a&&(b=b||"Unknown",J(function(){var c=Mb(a,b,e);K(c,B)}))},trackContentImpressionsWithinNode:function(a){!ca(Q)&&a&&J(function(){ja?Ha(function(){var b=n.findContentNodesWithinNode(a),b=fb(b);ya(b,B)}):gb(function(){var b=n.findContentNodesWithinNode(a),b=Ga(b);ya(b,B)})})},trackContentInteraction:function(a,b,e,c){!ca(Q)&&a&&b&&(e=e||"Unknown",
J(function(){var d=ua(a,b,e,c);K(d,B)}))},trackContentInteractionNode:function(a,b){!ca(Q)&&a&&J(function(){var e=Nb(a,b);K(e,B)})},trackEvent:function(a,b,e,c){J(function(){Ob(a,b,e,c)})},trackSiteSearch:function(a,e,c){J(function(){var d=D("search="+x(a)+(e?"&search_cat="+x(e):"")+(b(c)?"&search_count="+c:""),void 0,"sitesearch");K(d,B)})},setEcommerceView:function(a,e,c,d){b(c)&&c.length?c instanceof Array&&(c=JSON2.stringify(c)):c="";ea[5]=["_pkc",c];b(d)&&String(d).length&&(ea[2]=["_pkp",d]);
if(b(a)&&a.length||b(e)&&e.length)b(a)&&a.length&&(ea[3]=["_pks",a]),b(e)&&e.length||(e=""),ea[4]=["_pkn",e]},addEcommerceItem:function(a,b,e,c,d){a.length&&(y[a]=[a,b,e,c,d])},trackEcommerceOrder:function(a,e,c,d,f,g){String(a).length&&b(e)&&Bb(a,e,c,d,f,g)},trackEcommerceCartUpdate:function(a){b(a)&&Bb("",a,"","","","")},startPing:function(a,b){function e(){if(!0===Ra){Ra=!1;var a=objEvents.getReguest();0<a.events.length&&(a=objTools.serialize(a),ba(a,b))}}a=0>=a?5E3:a;b=b||"//a.ria.ru/ping";var c=
!1,d=ma();f(q,"click",C);f(q,"mouseup",C);f(q,"mousedown",C);f(q,"mousemove",C);f(q,"mousewheel",C);f(l,"DOMMouseScroll",C);f(l,"scroll",C);f(q,"keypress",C);f(q,"keydown",C);f(q,"keyup",C);f(l,"resize",C);f(l,"focus",C);f(l,"blur",C);f(l,"scroll",function(){!1===c&&(c=!0,setTimeout(e,2E3,!0))});objEvents.setRequestVar("idsite",Q);objEvents.setRequestVar("url",x(z(qa||Ua)));objEvents.setRequestVar("_id",d[1]);objEvents.setRequestVar("_idts",d[2]);setTimeout(function Oa(){e();pingTimerID=setTimeout(Oa,
a)},a)}}}var pa,ka={},q=document,F=navigator,Zb=screen,l=window,ia=l.performance||l.mozPerformance||l.msPerformance||l.webkitPerformance,la=!1,La=[],x=l.encodeURIComponent,kb=l.decodeURIComponent,lb=unescape,H,G,va,k={htmlCollectionToArray:function(a){var b=[],c;if(!a||!a.length)return b;for(c=0;c<a.length;c++)b.push(a[c]);return b},find:function(a){if(!document.querySelectorAll||!a)return[];a=document.querySelectorAll(a);return this.htmlCollectionToArray(a)},findMultiple:function(a){if(!a||!a.length)return[];
var b,c,d=[];for(b=0;b<a.length;b++)c=this.find(a[b]),d=d.concat(c);return d=this.makeNodesUnique(d)},findNodesByTagName:function(a,b){if(!a||!b||!a.getElementsByTagName)return[];var c=a.getElementsByTagName(b);return this.htmlCollectionToArray(c)},makeNodesUnique:function(a){var b=[].concat(a);a.sort(function(a,c){if(a===c)return 0;var d=ba(b,a),f=ba(b,c);return d===f?0:d>f?-1:1});if(1>=a.length)return a;var c=0,d=0,f=[],g;for(g=a[c++];g;)g===a[c]&&(d=f.push(c)),g=a[c++]||null;for(;d--;)a.splice(f[d],
1);return a},getAttributeValueFromNode:function(a,b){if(this.hasNodeAttribute(a,b)){if(a&&a.getAttribute)return a.getAttribute(b);if(a&&a.attributes&&"undefined"!==typeof a.attributes[b]){if(a.attributes[b].value)return a.attributes[b].value;if(a.attributes[b].nodeValue)return a.attributes[b].nodeValue;var c,d=a.attributes;if(d){for(c=0;c<d.length;c++)if(d[c].nodeName===b)return d[c].nodeValue;return null}}}},hasNodeAttributeWithValue:function(a,b){return!!this.getAttributeValueFromNode(a,b)},hasNodeAttribute:function(a,
b){return a&&a.hasAttribute?a.hasAttribute(b):a&&a.attributes?"undefined"!==typeof a.attributes[b]:!1},hasNodeCssClass:function(a,b){if(a&&b&&a.className){var c=a.className.split(" ");if(-1!==ba(c,b))return!0}return!1},findNodesHavingAttribute:function(a,b,c){c||(c=[]);if(!a||!b)return c;a=r(a);if(!a||!a.length)return c;var d,f;for(d=0;d<a.length;d++)f=a[d],this.hasNodeAttribute(f,b)&&c.push(f),c=this.findNodesHavingAttribute(f,b,c);return c},findFirstNodeHavingAttribute:function(a,b){if(a&&b){if(this.hasNodeAttribute(a,
b))return a;var c=this.findNodesHavingAttribute(a,b);if(c&&c.length)return c[0]}},findFirstNodeHavingAttributeWithValue:function(a,b){if(a&&b){if(this.hasNodeAttributeWithValue(a,b))return a;var c=this.findNodesHavingAttribute(a,b);if(c&&c.length){var d;for(d=0;d<c.length;d++)if(this.getAttributeValueFromNode(c[d],b))return c[d]}}},findNodesHavingCssClass:function(a,b,c){c||(c=[]);if(!a||!b)return c;if(a.getElementsByClassName)return b=a.getElementsByClassName(b),this.htmlCollectionToArray(b);a=r(a);
if(!a||!a.length)return[];var d,f;for(d=0;d<a.length;d++)f=a[d],this.hasNodeCssClass(f,b)&&c.push(f),c=this.findNodesHavingCssClass(f,b,c);return c},findFirstNodeHavingClass:function(a,b){if(a&&b){if(this.hasNodeCssClass(a,b))return a;var c=this.findNodesHavingCssClass(a,b);if(c&&c.length)return c[0]}},isLinkElement:function(a){if(!a)return!1;a=String(a.nodeName).toLowerCase();return-1!==ba(["a","area"],a)},setAnyAttribute:function(a,b,c){a&&b&&(a.setAttribute?a.setAttribute(b,c):a[b]=c)}},n={CONTENT_ATTR:"data-track-content",
CONTENT_CLASS:"piwikTrackContent",CONTENT_NAME_ATTR:"data-content-name",CONTENT_PIECE_ATTR:"data-content-piece",CONTENT_PIECE_CLASS:"piwikContentPiece",CONTENT_TARGET_ATTR:"data-content-target",CONTENT_TARGET_CLASS:"piwikContentTarget",CONTENT_IGNOREINTERACTION_ATTR:"data-content-ignoreinteraction",CONTENT_IGNOREINTERACTION_CLASS:"piwikContentIgnoreInteraction",location:void 0,findContentNodes:function(){return k.findMultiple(["."+this.CONTENT_CLASS,"["+this.CONTENT_ATTR+"]"])},findContentNodesWithinNode:function(a){if(!a)return[];
var b=k.findNodesHavingCssClass(a,this.CONTENT_CLASS),c=k.findNodesHavingAttribute(a,this.CONTENT_ATTR);if(c&&c.length){var d;for(d=0;d<c.length;d++)b.push(c[d])}k.hasNodeAttribute(a,this.CONTENT_ATTR)?b.push(a):k.hasNodeCssClass(a,this.CONTENT_CLASS)&&b.push(a);return b=k.makeNodesUnique(b)},findParentContentNode:function(a){if(a)for(var b=0;a&&a!==q&&a.parentNode;){if(k.hasNodeAttribute(a,this.CONTENT_ATTR)||k.hasNodeCssClass(a,this.CONTENT_CLASS))return a;a=a.parentNode;if(1E3<b)break;b++}},findPieceNode:function(a){var b;
(b=k.findFirstNodeHavingAttribute(a,this.CONTENT_PIECE_ATTR))||(b=k.findFirstNodeHavingClass(a,this.CONTENT_PIECE_CLASS));return b?b:a},findTargetNodeNoDefault:function(a){if(a){var b=k.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_TARGET_ATTR);if(b||(b=k.findFirstNodeHavingAttribute(a,this.CONTENT_TARGET_ATTR))||(b=k.findFirstNodeHavingClass(a,this.CONTENT_TARGET_CLASS)))return b}},findTargetNode:function(a){var b=this.findTargetNodeNoDefault(a);return b?b:a},findContentName:function(a){if(a){var b=
k.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_NAME_ATTR);if(b)return k.getAttributeValueFromNode(b,this.CONTENT_NAME_ATTR);if(b=this.findContentPiece(a))return this.removeDomainIfIsInLink(b);if(k.hasNodeAttributeWithValue(a,"title"))return k.getAttributeValueFromNode(a,"title");b=this.findPieceNode(a);if(k.hasNodeAttributeWithValue(b,"title"))return k.getAttributeValueFromNode(b,"title");a=this.findTargetNode(a);if(k.hasNodeAttributeWithValue(a,"title"))return k.getAttributeValueFromNode(a,
"title")}},findContentPiece:function(a){if(a){var b=k.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_PIECE_ATTR);if(b)return k.getAttributeValueFromNode(b,this.CONTENT_PIECE_ATTR);a=this.findPieceNode(a);if(a=this.findMediaUrlInNode(a))return this.toAbsoluteUrl(a)}},findContentTarget:function(a){if(a){var b=this.findTargetNode(a);if(k.hasNodeAttributeWithValue(b,this.CONTENT_TARGET_ATTR))return k.getAttributeValueFromNode(b,this.CONTENT_TARGET_ATTR);if(k.hasNodeAttributeWithValue(b,"href"))return a=
k.getAttributeValueFromNode(b,"href"),this.toAbsoluteUrl(a);a=this.findPieceNode(a);if(k.hasNodeAttributeWithValue(a,"href"))return a=k.getAttributeValueFromNode(a,"href"),this.toAbsoluteUrl(a)}},isSameDomain:function(a){if(!a||!a.indexOf)return!1;if(0===a.indexOf(this.getLocation().origin))return!0;a=a.indexOf(this.getLocation().host);return 8>=a&&0<=a?!0:!1},removeDomainIfIsInLink:function(a){a&&a.search&&-1!==a.search(/^https?:\/\/[^/]+/)&&this.isSameDomain(a)&&((a=a.replace(/^.*\/\/[^/]+/,""))||
(a="/"));return a},findMediaUrlInNode:function(a){if(a){var b=a.nodeName.toLowerCase();if(-1!==ba(["img","embed","video","audio"],b)&&k.findFirstNodeHavingAttributeWithValue(a,"src"))return a=k.findFirstNodeHavingAttributeWithValue(a,"src"),k.getAttributeValueFromNode(a,"src");if("object"===b&&k.hasNodeAttributeWithValue(a,"data"))return k.getAttributeValueFromNode(a,"data");if("object"===b){if((b=k.findNodesByTagName(a,"param"))&&b.length){var c;for(c=0;c<b.length;c++)if("movie"===k.getAttributeValueFromNode(b[c],
"name")&&k.hasNodeAttributeWithValue(b[c],"value"))return k.getAttributeValueFromNode(b[c],"value")}if((a=k.findNodesByTagName(a,"embed"))&&a.length)return this.findMediaUrlInNode(a[0])}}},trim:function(a){return a&&String(a)===a?a.replace(/^\s+|\s+$/g,""):a},isOrWasNodeInViewport:function(a){if(!a||!a.getBoundingClientRect||1!==a.nodeType)return!0;var b=a.getBoundingClientRect(),c=q.documentElement||{},d=0>b.top;d&&a.offsetTop&&(d=0<a.offsetTop+b.height);a=c.clientWidth;l.innerWidth&&a>l.innerWidth&&
(a=l.innerWidth);c=c.clientHeight;l.innerHeight&&c>l.innerHeight&&(c=l.innerHeight);return(0<b.bottom||d)&&0<b.right&&b.left<a&&(b.top<c||d)},isNodeVisible:function(a){var b=mb(a);a=this.isOrWasNodeInViewport(a);return b&&a},buildInteractionRequestParams:function(a,b,c,d){var f="";a&&(f+="c_i="+x(a));b&&(f&&(f+="&"),f+="c_n="+x(b));c&&(f&&(f+="&"),f+="c_p="+x(c));d&&(f&&(f+="&"),f+="c_t="+x(d));return f},buildImpressionRequestParams:function(a,b,c){a="c_n="+x(a)+"&c_p="+x(b);c&&(a+="&c_t="+x(c));
return a},buildContentBlock:function(a){if(a){var b=this.findContentName(a),c=this.findContentPiece(a);a=this.findContentTarget(a);b=this.trim(b);c=this.trim(c);a=this.trim(a);return{name:b||"Unknown",piece:c||"Unknown",target:a||""}}},collectContent:function(a){if(!a||!a.length)return[];var c=[],d,f;for(d=0;d<a.length;d++)f=this.buildContentBlock(a[d]),b(f)&&c.push(f);return c},setLocation:function(a){this.location=a},getLocation:function(){var a=this.location||l.location;a.origin||(a.origin=a.protocol+
"//"+a.hostname+(a.port?":"+a.port:""));return a},toAbsoluteUrl:function(a){return a&&String(a)===a||""===a?""===a?this.getLocation().href:-1!==a.search(/^\/\//)?this.getLocation().protocol+a:-1!==a.search(/:\/\//)?a:0===a.indexOf("#")||0===a.indexOf("?")?this.getLocation().origin+this.getLocation().pathname+a:0===a.search("^[a-zA-Z]{2,11}:")?a:-1!==a.search(/^\//)?this.getLocation().origin+a:this.getLocation().origin+this.getLocation().pathname.match(/(.*\/)/)[0]+a:a},isUrlToCurrentDomain:function(a){a=
this.toAbsoluteUrl(a);if(!a)return!1;var b=this.getLocation().origin;return b===a?!0:0===String(a).indexOf(b)?":"===String(a).substr(b.length,1)?!1:!0:!1},setHrefAttribute:function(a,b){a&&b&&k.setAnyAttribute(a,"href",b)},shouldIgnoreInteraction:function(a){var b=k.hasNodeAttribute(a,this.CONTENT_IGNOREINTERACTION_ATTR);a=k.hasNodeCssClass(a,this.CONTENT_IGNOREINTERACTION_CLASS);return b||a}};f(l,"beforeunload",function(){var a;v("unload");if(pa){do a=new Date;while(a.getTimeAlias()<pa)}},!1);(function(){var a;
q.addEventListener?f(q,"DOMContentLoaded",function P(){q.removeEventListener("DOMContentLoaded",P,!1);z()}):q.attachEvent&&(q.attachEvent("onreadystatechange",function p(){"complete"===q.readyState&&(q.detachEvent("onreadystatechange",p),z())}),q.documentElement.doScroll&&l===l.top&&function ac(){if(!la){try{q.documentElement.doScroll("left")}catch(a){setTimeout(ac,0);return}z()}}());/WebKit/.test(F.userAgent)&&(a=setInterval(function(){if(la||/loaded|complete/.test(q.readyState))clearInterval(a),
z()},10));f(l,"load",z,!1)})();Date.prototype.getTimeAlias=Date.prototype.getTime;H=new na;var fa={setTrackerUrl:1,setAPIUrl:1,setSiteId:1,disableCookies:1,enableLinkTracking:1,setMetadata:1,setResperfMarker:1,setCDNMask:1},R;for(G=0;G<_paq.length;G++)R=_paq[G][0],fa[R]&&(d(_paq[G]),delete _paq[G],1<fa[R]&&void 0!==console&&console&&console.error&&console.error("The method "+R+' is registered more than once in "_paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation: http://developer.piwik.org/api-reference/tracking-javascript#multiple-piwik-trackers'),
fa[R]++);for(G=0;G<_paq.length;G++)_paq[G]&&d(_paq[G]);_paq=new function(){return{push:d}};va={addPlugin:function(a,b){ka[a]=b},getTracker:function(a,b){return new na(a,b,H.getVisitorId())},getAsyncTracker:function(){return H}};"function"===typeof define&&define.amd&&define("piwik",[],function(){return va});return va}());window&&window.piwikAsyncInit&&window.piwikAsyncInit();(function(){"undefined"===typeof AnalyticsTracker&&(AnalyticsTracker=Piwik)})();
if("function"!==typeof piwik_log)var piwik_log=function(b,c,m,g){function d(b){try{return eval("piwik_"+b)}catch(c){}}var f=Piwik.getTracker(m,c);f.setDocumentTitle(b);f.setCustomData(g);(b=d("tracker_pause"))&&f.setLinkTrackingTimer(b);(b=d("download_extensions"))&&f.setDownloadExtensions(b);(b=d("hosts_alias"))&&f.setDomains(b);(b=d("ignore_classes"))&&f.setIgnoreClasses(b);f.trackPageView();d("install_tracker")&&(piwik_track=function(b,c,d,g){f.setSiteId(c);f.setTrackerUrl(d);f.trackLink(b,g)},
f.enableLinkTracking())};var _paq=_paq||[];_paq.push(["startPing",500]);
