var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(p,t,h){if(h.get||h.set)throw new TypeError("ES3 does not support getters and setters.");p!=Array.prototype&&p!=Object.prototype&&(p[t]=h.value)};$jscomp.getGlobal=function(p){return"undefined"!=typeof window&&window===p?p:"undefined"!=typeof global&&null!=global?global:p};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(p,t,h,r){if(t){h=$jscomp.global;p=p.split(".");for(r=0;r<p.length-1;r++){var k=p[r];k in h||(h[k]={});h=h[k]}p=p[p.length-1];r=h[p];t=t(r);t!=r&&null!=t&&$jscomp.defineProperty(h,p,{configurable:!0,writable:!0,value:t})}};$jscomp.polyfill("Array.prototype.fill",function(p){return p?p:function(p,h,r){var k=this.length||0;0>h&&(h=Math.max(0,k+h));if(null==r||r>k)r=k;r=Number(r);0>r&&(r=Math.max(0,k+r));for(h=Number(h||0);h<r;h++)this[h]=p;return this}},"es6-impl","es3");
(function(p,t){"function"===typeof define&&define.amd?define(t):"object"===typeof exports?module.exports=t():p.pickmeup=t()})(this,function(){function p(a,d,b){b=b||[];if(a instanceof Element)d.apply(d,[a].concat(b));else{var c,e;c=a.length;for(e=0;e<c;++e)d.apply(d,[a[e]].concat(b))}}function t(a){p(a,function(a){a.parentElement.removeChild(a)})}function h(a,d){var b=a;do b=b.parentElement;while(b&&!r(b,d));return b}function r(a,d){return(a.matches||a.webkitMatchesSelector||a.msMatchesSelector).call(a,
d)}function k(a,d){return a&&a.classList.contains(d)}function g(a,d){a.classList.add(d)}function w(a,d,b,c){if(-1!==b.indexOf(" ")){b=b.split(" ");var e=b.length,f;for(f=0;f<e;++f)w(a,d,b[f],c)}else a.__pickmeup.events.push([d,b,c]),d.addEventListener(b,c)}function y(a,d,b,c){var e,f,n;if(b&&-1!==b.indexOf(" "))for(e=b.split(" "),f=e.length,n=0;n<f;++n)y(a,d,e[n],c);else for(e=a.__pickmeup.events,f=e.length,n=0;n<f;++n)d&&d!=e[n][0]||b&&b!=e[n][1]||c&&c!=e[n][2]||e[n][0].removeEventListener(e[n][1],
e[n][2])}function I(a){a=a.getBoundingClientRect();return{top:a.top+window.pageYOffset-document.documentElement.clientTop,left:a.left+window.pageXOffset-document.documentElement.clientLeft}}function C(a,d,b){var c=document.createEvent("Event");b&&(c.detail=b);c.initEvent("pickmeup-"+d,!1,!0);return a.dispatchEvent(c)}function G(a){a=new Date(a);for(var d=28,b=a.getMonth();a.getMonth()==b;)++d,a.setDate(d);return d-1}function z(a,d){a.setDate(a.getDate()+d)}function u(a,d){var b=a.getDate();a.setDate(1);
a.setMonth(a.getMonth()+d);a.setDate(Math.min(b,G(a)))}function A(a,d){var b=a.getDate();a.setDate(1);a.setFullYear(a.getFullYear()+d);a.setDate(Math.min(b,G(a)))}function J(a){var d=a.__pickmeup.element,b=a.__pickmeup.options,c=Math.floor(b.calendars/2),e=b.current,f=b.min?new Date(b.min):null,n=b.max?new Date(b.max):null,l,p,k,q,m;f&&(f.setDate(1),u(f,1),z(f,-1));n&&(n.setDate(1),u(n,1),z(n,-1));t(Array.prototype.slice.call(d.querySelectorAll(".pmu-instance > :not(nav)")));for(var h=0;h<b.calendars;h++){l=
new Date(e);v(l);k=Array.prototype.slice.call(d.querySelectorAll(".pmu-instance"))[h];u(l,h-c);p=B(l,b.title_format,b.locales[b.locale]);header2=B(l,b.title_format2,b.locales[b.locale]);if(!m&&n&&(m=new Date(l),b.select_day?u(m,b.calendars-1):b.select_month?A(m,b.calendars-1):A(m,12*(b.calendars-1)),m>n)){--h;u(e,-1);m=void 0;continue}m=new Date(l);if(!q&&(q=new Date(l),q.setDate(1),u(q,1),z(q,-1),f&&f>q)){--h;u(e,1);q=void 0;continue}k.querySelector(".pmu-month").innerHTML=p+" <span>"+header2+"</span>";
(function(){var a=[],c=l.getMonth(),d=v(new Date).valueOf(),e,f,n,m,q,h;(function(){l.setDate(1);var a=(l.getDay()-b.first_day)%7;z(l,-(a+(0>a?7:0)))})();for(e=0;42>e;++e){f=document.createElement("div");f.textContent=l.getDate();f.__pickmeup_day=l.getDate();f.__pickmeup_month=l.getMonth();f.__pickmeup_year=l.getFullYear();c!=l.getMonth()&&g(f,"pmu-not-in-month");0==l.getDay()?g(f,"pmu-sunday"):6==l.getDay()&&g(f,"pmu-saturday");n=b.render(new Date(l))||{};m=v(new Date(l)).valueOf();q=b.min&&b.min>
l||b.max&&b.max<l;h=b.date.valueOf()==m||b.date instanceof Array&&b.date.reduce(function(a,b){return a||m===b.valueOf()},!1)||"range"==b.mode&&m>=b.date[0]&&m<=b.date[1];if(n.disabled||!("disabled"in n)&&q)g(f,"pmu-disabled");else if(n.selected||!("selected"in n)&&h)g(f,"pmu-selected"),v(new Date(l)).valueOf()==v(new Date(b.date[0])).valueOf()&&g(f,"pmu-selected-first"),v(new Date(l)).valueOf()==v(new Date(b.date[1])).valueOf()&&g(f,"pmu-selected-last");m==d&&g(f,"pmu-today");n.class_name&&n.class_name.split(" ").forEach(g.bind(f,
f));a.push(f);z(l,1)}k.appendChild(b.instance_content_template(a,"pmu-days"))})()}q.setDate(1);m.setDate(1);u(m,1);z(m,-1);c=d.querySelector(".pmu-prev");d=d.querySelector(".pmu-next");c&&(c.style.visibility=b.min&&b.min>=q?"hidden":"visible");d&&(d.style.visibility=b.max&&b.max<=m?"hidden":"visible");C(a,"fill")}function x(a,d){var b=d.format,c=d.separator,e=d.locales[d.locale];if(a instanceof Date||a instanceof Number)return v(new Date(a));if(!a)return v(new Date);if(a instanceof Array){a=a.slice();
for(b=0;b<a.length;++b)a[b]=x(a[b],d);return a}var f=a.split(c);if(1<f.length)return f.forEach(function(a,b,c){c[b]=x(a.trim(),d)}),f;for(var c=[].concat(e.daysShort,e.daysMin,e.days,e.monthsShort,e.months),c=c.map(function(a){return"("+a+")"}),c=new RegExp("[^0-9a-zA-Z"+c.join("")+"]+"),f=a.split(c),c=b.split(c),n,l,h,k,q,m=new Date,b=0;b<f.length;b++)switch(c[b]){case "b":l=e.monthsShort.indexOf(f[b]);break;case "B":l=e.months.indexOf(f[b]);break;case "d":case "e":n=parseInt(f[b],10);break;case "m":l=
parseInt(f[b],10)-1;break;case "Y":case "y":h=parseInt(f[b],10);h+=100<h?0:29>h?2E3:1900;break;case "H":case "I":case "k":case "l":k=parseInt(f[b],10);break;case "P":case "p":/pm/i.test(f[b])&&12>k?k+=12:/am/i.test(f[b])&&12<=k&&(k-=12);break;case "M":q=parseInt(f[b],10)}e=new Date(void 0===h?m.getFullYear():h,void 0===l?m.getMonth():l,void 0===n?m.getDate():n,void 0===k?m.getHours():k,void 0===q?m.getMinutes():q,0);isNaN(1*e)&&(e=new Date);return v(e)}function v(a){a.setHours(0,0,0,0);return a}function B(a,
d,b){var c=a.getMonth(),e=a.getDate(),f=a.getFullYear(),n=a.getDay(),l=a.getHours(),h=12<=l,k=h?l-12:l,q;q=new Date(a.getFullYear(),a.getMonth(),a.getDate(),0,0,0);var m=new Date(a.getFullYear(),0,0,0,0,0);q=Math.floor((q-m)/864E5);0==k&&(k=12);var m=a.getMinutes(),p=a.getSeconds();d=d.split("");for(var g,r=0;r<d.length;r++){g=d[r];switch(g){case "a":g=b.daysShort[n];break;case "A":g=b.days[n];break;case "b":g=b.monthsShort[c];break;case "B":g=b.months[c];break;case "C":g=1+Math.floor(f/100);break;
case "d":g=10>e?"0"+e:e;break;case "e":g=e;break;case "H":g=10>l?"0"+l:l;break;case "I":g=10>k?"0"+k:k;break;case "j":g=100>q?10>q?"00"+q:"0"+q:q;break;case "k":g=l;break;case "l":g=k;break;case "m":g=9>c?"0"+(1+c):1+c;break;case "M":g=10>m?"0"+m:m;break;case "p":case "P":g=h?"PM":"AM";break;case "s":g=Math.floor(a.getTime()/1E3);break;case "S":g=10>p?"0"+p:p;break;case "u":g=n+1;break;case "w":g=n;break;case "y":g=(""+f).substr(2,2);break;case "Y":g=f}d[r]=g}return d.join("")}function K(a,d){var b=
a.__pickmeup.options,c;v(d);a:{var e;switch(b.mode){case "multiple":e=d.valueOf();for(c=0;c<b.date.length;++c)if(b.date[c].valueOf()===e){b.date.splice(c,1);break a}b.date.push(d);break;case "range":b.lastSel||(b.date[0]=d);d<=b.date[0]?(b.date[1]=b.date[0],b.date[0]=d):b.date[1]=d;b.lastSel=!b.lastSel;break;default:b.date=d.valueOf()}}c=E(b);r(a,"input")&&(a.value="single"==b.mode?c.formatted_date:c.formatted_date.join(b.separator));C(a,"change",c);b.flat||!b.hide_on_select||"range"==b.mode&&b.lastSel||
b.bound.hide()}function L(a,d){var b=d.target;k(b,"pmu-button")||(b=h(b,".pmu-button"));if(!k(b,"pmu-button")||k(b,"pmu-disabled"))return!1;d.preventDefault();d.stopPropagation();var c=a.__pickmeup.options,e=h(b,".pmu-instance"),f=e.parentElement,e=Array.prototype.slice.call(f.querySelectorAll(".pmu-instance")).indexOf(e);r(b.parentElement,"nav")?k(b,"pmu-month")?(u(c.current,e-Math.floor(c.calendars/2)),k(f,"pmu-view-years")?(c.current="single"!=c.mode?new Date(c.date[c.date.length-1]):new Date(c.date),
c.select_day?(f.classList.remove("pmu-view-years"),g(f,"pmu-view-days")):c.select_month&&(f.classList.remove("pmu-view-years"),g(f,"pmu-view-months"))):k(f,"pmu-view-months")?c.select_year?(f.classList.remove("pmu-view-months"),g(f,"pmu-view-years")):c.select_day&&(f.classList.remove("pmu-view-months"),g(f,"pmu-view-days")):k(f,"pmu-view-days")&&(c.select_month?(f.classList.remove("pmu-view-days"),g(f,"pmu-view-months")):c.select_year&&(f.classList.remove("pmu-view-days"),g(f,"pmu-view-years")))):
k(b,"pmu-prev")?c.bound.prev(!1):c.bound.next(!1):k(f,"pmu-view-years")?(c.current.setFullYear(b.__pickmeup_year),c.select_month?(f.classList.remove("pmu-view-years"),g(f,"pmu-view-months")):c.select_day?(f.classList.remove("pmu-view-years"),g(f,"pmu-view-days")):c.bound.update_date(c.current)):k(f,"pmu-view-months")?(c.current.setMonth(b.__pickmeup_month),c.current.setFullYear(b.__pickmeup_year),c.select_day?(f.classList.remove("pmu-view-months"),g(f,"pmu-view-days")):c.bound.update_date(c.current),
u(c.current,Math.floor(c.calendars/2)-e)):(f=new Date(c.current),f.setYear(b.__pickmeup_year),f.setMonth(b.__pickmeup_month),f.setDate(b.__pickmeup_day),c.bound.update_date(f));c.bound.fill();return!0}function E(a){var d;if("single"==a.mode)return d=new Date(a.date),{formatted_date:B(d,a.format,a.locales[a.locale]),date:d};d={formatted_date:[],date:[]};a.date.forEach(function(b){b=new Date(b);d.formatted_date.push(B(b,a.format,a.locales[a.locale]));d.date.push(b)});return d}function F(a,d){var b=
a.__pickmeup.element,c;if(d||k(b,"pmu-hidden")){var e=a.__pickmeup.options,f=I(a),g=window.pageXOffset,l=window.pageYOffset,h=document.documentElement.clientWidth,p=document.documentElement.clientHeight,q=f.top,m=f.left;e.bound.fill();r(a,"input")&&((c=a.value)&&e.bound.set_date(c),w(a,a,"keydown",function(a){9==a.which&&e.bound.hide()}),e.lastSel=!1);if(C(a,"show")&&!e.flat){b.classList.remove("pmu-hidden");if(e.position instanceof Function)f=e.position.call(a),m=f.left,q=f.top;else{switch(e.position){case "top":q-=
b.offsetHeight;break;case "left":m-=b.offsetWidth;break;case "right":m+=a.offsetWidth;break;case "bottom":q+=a.offsetHeight}q+b.offsetHeight>l+p&&(q=f.top-b.offsetHeight);q<l&&(q=f.top+a.offsetHeight);m+b.offsetWidth>g+h&&(m=f.left-b.offsetWidth);m<g&&(m=f.left+a.offsetWidth);m+="px";q+="px"}b.style.left=m;b.style.top=q;setTimeout(function(){w(a,document.documentElement,"click",e.bound.hide);w(a,window,"resize",e.bound.forced_show)})}}}function M(a,d){var b=a.__pickmeup.element,c=a.__pickmeup.options;
d&&d.target&&(d.target==a||b.compareDocumentPosition(d.target)&16)||!C(a,"hide")||(g(b,"pmu-hidden"),y(a,document.documentElement,"click",c.bound.hide),y(a,window,"resize",c.bound.forced_show),c.lastSel=!1)}function N(a){var d=a.__pickmeup.options;y(a,document.documentElement,"click",d.bound.hide);y(a,window,"resize",d.bound.forced_show);d.bound.forced_show()}function O(a){a=a.__pickmeup.options;"single"!=a.mode&&(a.date=[],a.lastSel=!1,a.bound.fill())}function P(a,d){"undefined"==typeof d&&(d=!0);
var b=a.__pickmeup.element,c=a.__pickmeup.options;k(b,"pmu-view-years")?A(c.current,-12):k(b,"pmu-view-months")?A(c.current,-1):k(b,"pmu-view-days")&&u(c.current,-1);d&&c.bound.fill()}function Q(a,d){"undefined"==typeof d&&(d=!0);var b=a.__pickmeup.element,c=a.__pickmeup.options;k(b,"pmu-view-years")?A(c.current,12):k(b,"pmu-view-months")?A(c.current,1):k(b,"pmu-view-days")&&u(c.current,1);d&&c.bound.fill()}function R(a,d){var b=a.__pickmeup.options,c=E(b);return"string"===typeof d?(c=c.date,c instanceof
Date?B(c,d,b.locales[b.locale]):c.map(function(a){return B(a,d,b.locales[b.locale])})):c[d?"formatted_date":"date"]}function S(a,d,b){var c=a.__pickmeup.options;if(!(d instanceof Array)||0<d.length)if(c.date=x(d,c),"single"!=c.mode)for(c.date instanceof Array?(c.date[0]=c.date[0]||x(new Date,c),"range"==c.mode&&(c.date[1]=c.date[1]||x(c.date[0],c))):(c.date=[c.date],"range"==c.mode&&c.date.push(x(c.date[0],c))),d=0;d<c.date.length;++d)c.date[d]=H(c.date[d],c.min,c.max);else c.date instanceof Array&&
(c.date=c.date[0]),c.date=H(c.date,c.min,c.max);else c.date=[];if(!c.select_day)if(c.date instanceof Array)for(d=0;d<c.date.length;++d)c.date[d].setDate(1);else c.date.setDate(1);if("multiple"==c.mode)for(d=0;d<c.date.length;++d)c.date.indexOf(c.date[d])!==d&&(c.date.splice(d,1),--d);b?c.current=x(b,c):(b="single"===c.mode?c.date:c.date[c.date.length-1],c.current=b?new Date(b):new Date);c.current.setDate(1);c.bound.fill();r(a,"input")&&!1!==c.default_date&&(b=E(c),d=a.value,c="single"==c.mode?b.formatted_date:
b.formatted_date.join(c.separator),d||C(a,"change",b),d!=c&&(a.value=c))}function T(a){var d=a.__pickmeup.element;y(a);t(d);delete a.__pickmeup}function H(a,d,b){return d&&d>a?new Date(d):b&&b<a?new Date(b):a}function D(a,d){"string"==typeof a&&(a=document.querySelector(a));if(!a)return null;if(!a.__pickmeup){var b,c,e={};d=d||{};for(b in D.defaults)e[b]=b in d?d[b]:D.defaults[b];for(b in e)c=a.getAttribute("data-pmu-"+b),null!==c&&(e[b]=c);"days"!=e.view||e.select_day||(e.view="months");"months"!=
e.view||e.select_month||(e.view="years");"years"!=e.view||e.select_year||(e.view="days");"days"!=e.view||e.select_day||(e.view="months");e.calendars=Math.max(1,parseInt(e.calendars,10)||1);e.mode=/single|multiple|range/.test(e.mode)?e.mode:"single";e.min&&(e.min=x(e.min,e),e.select_day||e.min.setDate(1));e.max&&(e.max=x(e.max,e),e.select_day||e.max.setDate(1));c=document.createElement("div");a.__pickmeup={options:e,events:[],element:c};c.__pickmeup_target=a;g(c,"pickmeup");e.class_name&&g(c,e.class_name);
e.bound={fill:J.bind(a,a),update_date:K.bind(a,a),click:L.bind(a,a),show:F.bind(a,a),forced_show:F.bind(a,a,!0),hide:M.bind(a,a),update:N.bind(a,a),clear:O.bind(a,a),prev:P.bind(a,a),next:Q.bind(a,a),get_date:R.bind(a,a),set_date:S.bind(a,a),destroy:T.bind(a,a)};g(c,"pmu-view-"+e.view);var f=e.instance_template(e),h="";for(b=0;b<e.calendars;++b)h+=f;c.innerHTML=h;w(a,c,"click",e.bound.click);w(a,c,"onselectstart"in Element.prototype?"selectstart":"mousedown",function(a){a.preventDefault()});e.flat?
(g(c,"pmu-flat"),a.appendChild(c)):(g(c,"pmu-hidden"),document.body.appendChild(c),w(a,a,"click",F.bind(a,a,!1)),w(a,a,"input",e.bound.update),w(a,a,"change",e.bound.update));e.bound.set_date(e.date,e.current)}e=a.__pickmeup.options;return{hide:e.bound.hide,show:e.bound.show,clear:e.bound.clear,update:e.bound.update,prev:e.bound.prev,next:e.bound.next,get_date:e.bound.get_date,set_date:e.bound.set_date,destroy:e.bound.destroy}}D.defaults={current:null,date:new Date,default_date:new Date,flat:!1,first_day:1,
prev:"&#9664;",next:"&#9654;",mode:"single",select_year:!1,select_month:!1,select_day:!0,view:"days",calendars:1,format:"d-m-Y",title_format:"B",title_format2:"Y",position:"bottom",class_name:"",separator:" - ",hide_on_select:!1,min:null,max:null,render:function(){},locale:"ru",locales:{en:{days:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),daysShort:"Sun Mon Tue Wed Thu Fri Sat".split(" "),daysMin:"Su Mo Tu We Th Fr Sa".split(" "),months:"January February March April May June July August September October November December".split(" "),
monthsShort:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ")},ru:{daysMin:[],months:"\u042f\u043d\u0432\u0430\u0440\u044c \u0424\u0435\u0432\u0440\u0430\u043b\u044c \u041c\u0430\u0440\u0442 \u0410\u043f\u0440\u0435\u043b\u044c \u041c\u0430\u0439 \u0418\u044e\u043d\u044c \u0418\u044e\u043b\u044c \u0410\u0432\u0433\u0443\u0441\u0442 \u0421\u0435\u043d\u0442\u044f\u0431\u0440\u044c \u041e\u043a\u0442\u044f\u0431\u0440\u044c \u041d\u043e\u044f\u0431\u0440\u044c \u0414\u0435\u043a\u0430\u0431\u0440\u044c".split(" "),
monthsShort:[]}},instance_template:function(a){return'<div class="pmu-instance"><nav><div class="pmu-month"><span></span></div></nav></div>'},instance_content_template:function(a,d){var b=document.createElement("div");g(b,d);for(var c=0;c<a.length;++c)g(a[c],"pmu-button"),b.appendChild(a[c]);return b}};return D});
