var $jscomp={scope:{},findInternal:function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6-impl","es3");
$(function(){Profile=function(a){$.extend(this,{csrf_token:"",actions:{delete_field:"/services/id/profile/delete_field/",update_field:"/services/id/profile/update_field/",send_email:"/services/id/change_email/send_email/",change_privacy:"/services/id/profile/change_privacy/",change_password:"/services/id/profile/change_password/",delete_account:"/services/id/profile/delete_account/",delete_social:"/services/id/profile/delete_social/",update_avatar:"/services/id/profile/update_avatar/",send_message:"/services/id/profile/send_message/",
password_recovery:"/services/id/profile/password-recovery/"}},a)};Profile.prototype.updateField=function(a){a=a.serializeArray();a.push({name:"csrf_token",value:this.csrf_token});return $.ajax({url:this.actions.update_field,data:a,type:"post",dataType:"json"})};Profile.prototype.changePrivacy=function(a){a=a||{};a.csrf_token=this.csrf_token;return $.ajax({url:this.actions.update_field,data:a,type:"post",dataType:"json"})};Profile.prototype.passwordRecovery=function(){return $.ajax({url:this.actions.password_recovery,
type:"post",dataType:"json",data:{csrf_token:this.csrf_token}})};Profile.prototype.accountDelete=function(){return $.ajax({url:this.actions.delete_account,type:"post",dataType:"json",data:{csrf_token:this.csrf_token}})};Profile.prototype.socialDelete=function(a){return $.ajax({url:this.actions.delete_social,data:{provider:a,csrf_token:this.csrf_token},type:"post",dataType:"json"})};Profile.prototype.socialLink=function(a){function b(a){a=JSON.parse(a.data);"function"===typeof window.document[a.func]&&
(window.document[a.func](a.data,a.error),c&&c.close(),d&&clearInterval(d))}a=$.extend({name:"\u0410\u0432\u0442\u043e\u0440\u0438\u0437\u0430\u0446\u0438\u044f",params:"menubar=yes,location=yes,resizable=no,scrollbars=no,status=yes",width:"500",height:"300",provider:"",success:function(){}},a||{});var c=window.open(GLOBAL.auth[a.provider]+"?link=1",a.name,"top="+(screen.height-a.height)/2+",left="+(screen.width-a.width)/2+",width="+a.width+",height="+a.height+a.params),d;window.document.linkSocialAccountSuccess=
function(b){a.success(b)};window.document.linkSocialAccountError=function(a,b){console.error({field_name:b[0],error_code:b[1]})};window.addEventListener?window.addEventListener("message",b,!1):window.attachEvent("onmessage",b);d=setInterval(function(){c.postMessage("linkSocialAccount","*")},2E3)};Profile.prototype.showSocial=function(a){};Profile.prototype.alert=function(a){var b=$("#idProfileAlert");b.find(".l-modal__text span").html(a.text);b.find(".l-modal__confirm-yes").off("click.idProfileAlert");
if(a.onclose instanceof Function)b.on("click.idProfileAlert",".l-modal__confirm-yes",a.onclose);modalLayer.open("id_alert")};Profile.prototype.confirm=function(a){var b=$("#idProfileConfirm");b.find(".l-modal__text span").html(a.text);b.find(".l-modal__confirm-yes").off("click.idProfileConfirm");b.find(".l-modal__confirm-no").off("click.idProfileConfirm");if(a.onclose instanceof Function)b.on("click.idProfileConfirm",".l-modal__confirm-no",a.onclose);if(a.success instanceof Function)b.on("click.idProfileConfirm",
".l-modal__confirm-yes",a.success);modalLayer.open("id_confirm")};Profile.prototype.logout=function(){return $.ajax({url:"/services/id/logout/",type:"post",data:{csrf_token:GLOBAL.csrf_token}})}});
