/*
 jQuery UI - v1.12.1+CommonJS - 2018-02-10
 http://jqueryui.com
 Includes: widget.js
 Copyright jQuery Foundation and other contributors; Licensed MIT  jQuery UI Widget 1.12.1
 http://jqueryui.com

 Copyright jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,k,h){if(h.get||h.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[k]=h.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var k=0;return $jscomp.iteratorPrototype(function(){return k<a.length?{done:!1,value:a[k++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(a,k){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var h=0,b={next:function(){if(h<a.length){var c=h++;return{value:k(c,a[c]),done:!1}}b.next=function(){return{done:!0,value:void 0}};return b.next()}};b[Symbol.iterator]=function(){return b};return b};
$jscomp.polyfill=function(a,k,h,b){if(k){h=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var c=a[b];c in h||(h[c]={});h=h[c]}a=a[a.length-1];b=h[a];k=k(b);k!=b&&null!=k&&$jscomp.defineProperty(h,a,{configurable:!0,writable:!0,value:k})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");
(function(a){"function"===typeof define&&define.amd?define(["jquery"],a):"object"===typeof exports?a(require("jquery")):a(jQuery)})(function(a){a.ui=a.ui||{};a.ui.version="1.12.1";var k=0,h=Array.prototype.slice;a.cleanData=function(b){return function(c){var e,d,f;for(f=0;null!=(d=c[f]);f++)try{(e=a._data(d,"events"))&&e.remove&&a(d).triggerHandler("remove")}catch(g){}b(c)}}(a.cleanData);a.widget=function(b,c,e){var d,f,g,m={},l=b.split(".")[0];b=b.split(".")[1];var h=l+"-"+b;e||(e=c,c=a.Widget);
a.isArray(e)&&(e=a.extend.apply(null,[{}].concat(e)));a.expr[":"][h.toLowerCase()]=function(b){return!!a.data(b,h)};a[l]=a[l]||{};d=a[l][b];f=a[l][b]=function(a,b){if(!this._createWidget)return new f(a,b);arguments.length&&this._createWidget(a,b)};a.extend(f,d,{version:e.version,_proto:a.extend({},e),_childConstructors:[]});g=new c;g.options=a.widget.extend({},g.options);a.each(e,function(b,d){a.isFunction(d)?m[b]=function(){function a(){return c.prototype[b].apply(this,arguments)}function e(a){return c.prototype[b].apply(this,
a)}return function(){var b=this._super,c=this._superApply,f;this._super=a;this._superApply=e;f=d.apply(this,arguments);this._super=b;this._superApply=c;return f}}():m[b]=d});f.prototype=a.widget.extend(g,{widgetEventPrefix:d?g.widgetEventPrefix||b:b},m,{constructor:f,namespace:l,widgetName:b,widgetFullName:h});d?(a.each(d._childConstructors,function(b,c){var d=c.prototype;a.widget(d.namespace+"."+d.widgetName,f,c._proto)}),delete d._childConstructors):c._childConstructors.push(f);a.widget.bridge(b,
f);return f};a.widget.extend=function(b){for(var c=h.call(arguments,1),e=0,d=c.length,f,g;e<d;e++)for(f in c[e])g=c[e][f],c[e].hasOwnProperty(f)&&void 0!==g&&(a.isPlainObject(g)?b[f]=a.isPlainObject(b[f])?a.widget.extend({},b[f],g):a.widget.extend({},g):b[f]=g);return b};a.widget.bridge=function(b,c){var e=c.prototype.widgetFullName||b;a.fn[b]=function(d){var f="string"===typeof d,g=h.call(arguments,1),m=this;f?this.length||"instance"!==d?this.each(function(){var c,f=a.data(this,e);if("instance"===
d)return m=f,!1;if(!f)return a.error("cannot call methods on "+b+" prior to initialization; attempted to call method '"+d+"'");if(!a.isFunction(f[d])||"_"===d.charAt(0))return a.error("no such method '"+d+"' for "+b+" widget instance");c=f[d].apply(f,g);if(c!==f&&void 0!==c)return m=c&&c.jquery?m.pushStack(c.get()):c,!1}):m=void 0:(g.length&&(d=a.widget.extend.apply(null,[d].concat(g))),this.each(function(){var b=a.data(this,e);b?(b.option(d||{}),b._init&&b._init()):a.data(this,e,new c(d,this))}));
return m}};a.Widget=function(){};a.Widget._childConstructors=[];a.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",defaultElement:"<div>",options:{classes:{},disabled:!1,create:null},_createWidget:function(b,c){c=a(c||this.defaultElement||this)[0];this.element=a(c);this.uuid=k++;this.eventNamespace="."+this.widgetName+this.uuid;this.bindings=a();this.hoverable=a();this.focusable=a();this.classesElementLookup={};c!==this&&(a.data(c,this.widgetFullName,this),this._on(!0,this.element,{remove:function(b){b.target===
c&&this.destroy()}}),this.document=a(c.style?c.ownerDocument:c.document||c),this.window=a(this.document[0].defaultView||this.document[0].parentWindow));this.options=a.widget.extend({},this.options,this._getCreateOptions(),b);this._create();this.options.disabled&&this._setOptionDisabled(this.options.disabled);this._trigger("create",null,this._getCreateEventData());this._init()},_getCreateOptions:function(){return{}},_getCreateEventData:a.noop,_create:a.noop,_init:a.noop,destroy:function(){var b=this;
this._destroy();a.each(this.classesElementLookup,function(a,e){b._removeClass(e,a)});this.element.off(this.eventNamespace).removeData(this.widgetFullName);this.widget().off(this.eventNamespace).removeAttr("aria-disabled");this.bindings.off(this.eventNamespace)},_destroy:a.noop,widget:function(){return this.element},option:function(b,c){var e=b,d,f,g;if(0===arguments.length)return a.widget.extend({},this.options);if("string"===typeof b)if(e={},d=b.split("."),b=d.shift(),d.length){f=e[b]=a.widget.extend({},
this.options[b]);for(g=0;g<d.length-1;g++)f[d[g]]=f[d[g]]||{},f=f[d[g]];b=d.pop();if(1===arguments.length)return void 0===f[b]?null:f[b];f[b]=c}else{if(1===arguments.length)return void 0===this.options[b]?null:this.options[b];e[b]=c}this._setOptions(e);return this},_setOptions:function(b){for(var a in b)this._setOption(a,b[a]);return this},_setOption:function(b,a){"classes"===b&&this._setOptionClasses(a);this.options[b]=a;"disabled"===b&&this._setOptionDisabled(a);return this},_setOptionClasses:function(b){var c,
e,d;for(c in b)d=this.classesElementLookup[c],b[c]!==this.options.classes[c]&&d&&d.length&&(e=a(d.get()),this._removeClass(d,c),e.addClass(this._classes({element:e,keys:c,classes:b,add:!0})))},_setOptionDisabled:function(b){this._toggleClass(this.widget(),this.widgetFullName+"-disabled",null,!!b);b&&(this._removeClass(this.hoverable,null,"ui-state-hover"),this._removeClass(this.focusable,null,"ui-state-focus"))},enable:function(){return this._setOptions({disabled:!1})},disable:function(){return this._setOptions({disabled:!0})},
_classes:function(b){function c(c,g){var f,l;for(l=0;l<c.length;l++)f=d.classesElementLookup[c[l]]||a(),f=b.add?a(a.unique(f.get().concat(b.element.get()))):a(f.not(b.element).get()),d.classesElementLookup[c[l]]=f,e.push(c[l]),g&&b.classes[c[l]]&&e.push(b.classes[c[l]])}var e=[],d=this;b=a.extend({element:this.element,classes:this.options.classes||{}},b);this._on(b.element,{remove:"_untrackClassesElement"});b.keys&&c(b.keys.match(/\S+/g)||[],!0);b.extra&&c(b.extra.match(/\S+/g)||[]);return e.join(" ")},
_untrackClassesElement:function(b){var c=this;a.each(c.classesElementLookup,function(e,d){-1!==a.inArray(b.target,d)&&(c.classesElementLookup[e]=a(d.not(b.target).get()))})},_removeClass:function(b,a,e){return this._toggleClass(b,a,e,!1)},_addClass:function(a,c,e){return this._toggleClass(a,c,e,!0)},_toggleClass:function(a,c,e,d){d="boolean"===typeof d?d:e;var b="string"===typeof a||null===a;a={extra:b?c:e,keys:b?a:c,element:b?this.element:a,add:d};a.element.toggleClass(this._classes(a),d);return this},
_on:function(b,c,e){var d,f=this;"boolean"!==typeof b&&(e=c,c=b,b=!1);e?(c=d=a(c),this.bindings=this.bindings.add(c)):(e=c,c=this.element,d=this.widget());a.each(e,function(e,h){function g(){if(b||!0!==f.options.disabled&&!a(this).hasClass("ui-state-disabled"))return("string"===typeof h?f[h]:h).apply(f,arguments)}"string"!==typeof h&&(g.guid=h.guid=h.guid||g.guid||a.guid++);var k=e.match(/^([\w:-]*)\s*(.*)$/),m=k[1]+f.eventNamespace;if(k=k[2])d.on(m,k,g);else c.on(m,g)})},_off:function(b,c){c=(c||
"").split(" ").join(this.eventNamespace+" ")+this.eventNamespace;b.off(c).off(c);this.bindings=a(this.bindings.not(b).get());this.focusable=a(this.focusable.not(b).get());this.hoverable=a(this.hoverable.not(b).get())},_delay:function(a,c){var b=this;return setTimeout(function(){return("string"===typeof a?b[a]:a).apply(b,arguments)},c||0)},_hoverable:function(b){this.hoverable=this.hoverable.add(b);this._on(b,{mouseenter:function(b){this._addClass(a(b.currentTarget),null,"ui-state-hover")},mouseleave:function(b){this._removeClass(a(b.currentTarget),
null,"ui-state-hover")}})},_focusable:function(b){this.focusable=this.focusable.add(b);this._on(b,{focusin:function(b){this._addClass(a(b.currentTarget),null,"ui-state-focus")},focusout:function(b){this._removeClass(a(b.currentTarget),null,"ui-state-focus")}})},_trigger:function(b,c,e){var d,f=this.options[b];e=e||{};c=a.Event(c);c.type=(b===this.widgetEventPrefix?b:this.widgetEventPrefix+b).toLowerCase();c.target=this.element[0];if(b=c.originalEvent)for(d in b)d in c||(c[d]=b[d]);this.element.trigger(c,
e);return!(a.isFunction(f)&&!1===f.apply(this.element[0],[c].concat(e))||c.isDefaultPrevented())}};a.each({show:"fadeIn",hide:"fadeOut"},function(b,c){a.Widget.prototype["_"+b]=function(e,d,f){"string"===typeof d&&(d={effect:d});var g,h=d?!0===d||"number"===typeof d?c:d.effect||c:b;d=d||{};"number"===typeof d&&(d={duration:d});g=!a.isEmptyObject(d);d.complete=f;d.delay&&e.delay(d.delay);if(g&&a.effects&&a.effects.effect[h])e[b](d);else if(h!==b&&e[h])e[h](d.duration,d.easing,f);else e.queue(function(c){a(this)[b]();
f&&f.call(e[0]);c()})}})});
