var $jscomp={scope:{},findInternal:function(c,l,a){c instanceof String&&(c=String(c));for(var b=c.length,d=0;d<b;d++){var e=c[d];if(l.call(a,e,d,c))return{i:d,v:e}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(c,l,a){if(a.get||a.set)throw new TypeError("ES3 does not support getters and setters.");c!=Array.prototype&&c!=Object.prototype&&(c[l]=a.value)};
$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(c,l,a,b){if(l){a=$jscomp.global;c=c.split(".");for(b=0;b<c.length-1;b++){var d=c[b];d in a||(a[d]={});a=a[d]}c=c[c.length-1];b=a[c];l=l(b);l!=b&&null!=l&&$jscomp.defineProperty(a,c,{configurable:!0,writable:!0,value:l})}};
$jscomp.polyfill("Array.prototype.find",function(c){return c?c:function(c,a){return $jscomp.findInternal(this,c,a).v}},"es6-impl","es3");
(function(c){"function"===typeof define&&define.amd?define(["jquery","jquery-ui/ui/widget"],c):"object"===typeof exports?c(require("jquery"),require("./vendor/jquery.ui.widget")):c(window.jQuery)})(function(c){function l(a){var b="dragover"===a;return function(d){d.dataTransfer=d.originalEvent&&d.originalEvent.dataTransfer;var e=d.dataTransfer;e&&-1!==c.inArray("Files",e.types)&&!1!==this._trigger(a,c.Event(a,{delegatedEvent:d}))&&(d.preventDefault(),b&&(e.dropEffect="copy"))}}c.support.fileInput=
!(/(Android (1\.[0156]|2\.[01]))|(Windows Phone (OS 7|8\.0))|(XBLWP)|(ZuneWP)|(WPDesktop)|(w(eb)?OSBrowser)|(webOS)|(Kindle\/(1\.0|2\.[05]|3\.0))/.test(window.navigator.userAgent)||c('<input type="file"/>').prop("disabled"));c.support.xhrFileUpload=!(!window.ProgressEvent||!window.FileReader);c.support.xhrFormDataFileUpload=!!window.FormData;c.support.blobSlice=window.Blob&&(Blob.prototype.slice||Blob.prototype.webkitSlice||Blob.prototype.mozSlice);c.widget("blueimp.fileupload",{options:{dropZone:c(document),
pasteZone:void 0,fileInput:void 0,replaceFileInput:!0,paramName:void 0,singleFileUploads:!0,limitMultiFileUploads:void 0,limitMultiFileUploadSize:void 0,limitMultiFileUploadSizeOverhead:512,sequentialUploads:!1,limitConcurrentUploads:void 0,forceIframeTransport:!1,redirect:void 0,redirectParamName:void 0,postMessage:void 0,multipart:!0,maxChunkSize:void 0,uploadedBytes:void 0,recalculateProgress:!0,progressInterval:100,bitrateInterval:500,autoUpload:!0,messages:{uploadedBytes:"Uploaded bytes exceed file size"},
i18n:function(a,b){a=this.messages[a]||a.toString();b&&c.each(b,function(b,c){a=a.replace("{"+b+"}",c)});return a},formData:function(a){return a.serializeArray()},add:function(a,b){if(a.isDefaultPrevented())return!1;(b.autoUpload||!1!==b.autoUpload&&c(this).fileupload("option","autoUpload"))&&b.process().done(function(){b.submit()})},processData:!1,contentType:!1,cache:!1,timeout:0},_specialOptions:["fileInput","dropZone","pasteZone","multipart","forceIframeTransport"],_blobSlice:c.support.blobSlice&&
function(){return(this.slice||this.webkitSlice||this.mozSlice).apply(this,arguments)},_BitrateTimer:function(){this.timestamp=Date.now?Date.now():(new Date).getTime();this.bitrate=this.loaded=0;this.getBitrate=function(a,b,d){var c=a-this.timestamp;if(!this.bitrate||!d||c>d)this.bitrate=1E3/c*(b-this.loaded)*8,this.loaded=b,this.timestamp=a;return this.bitrate}},_isXHRUpload:function(a){return!a.forceIframeTransport&&(!a.multipart&&c.support.xhrFileUpload||c.support.xhrFormDataFileUpload)},_getFormData:function(a){var b;
return"function"===c.type(a.formData)?a.formData(a.form):c.isArray(a.formData)?a.formData:"object"===c.type(a.formData)?(b=[],c.each(a.formData,function(a,c){b.push({name:a,value:c})}),b):[]},_getTotal:function(a){var b=0;c.each(a,function(a,c){b+=c.size||1});return b},_initProgressObject:function(a){var b={loaded:0,total:0,bitrate:0};a._progress?c.extend(a._progress,b):a._progress=b},_initResponseObject:function(a){var b;if(a._response)for(b in a._response)a._response.hasOwnProperty(b)&&delete a._response[b];
else a._response={}},_onProgress:function(a,b){if(a.lengthComputable){var d=Date.now?Date.now():(new Date).getTime(),e;b._time&&b.progressInterval&&d-b._time<b.progressInterval&&a.loaded!==a.total||(b._time=d,e=Math.floor(a.loaded/a.total*(b.chunkSize||b._progress.total))+(b.uploadedBytes||0),this._progress.loaded+=e-b._progress.loaded,this._progress.bitrate=this._bitrateTimer.getBitrate(d,this._progress.loaded,b.bitrateInterval),b._progress.loaded=b.loaded=e,b._progress.bitrate=b.bitrate=b._bitrateTimer.getBitrate(d,
e,b.bitrateInterval),this._trigger("progress",c.Event("progress",{delegatedEvent:a}),b),this._trigger("progressall",c.Event("progressall",{delegatedEvent:a}),this._progress))}},_initProgressListener:function(a){var b=this,d=a.xhr?a.xhr():c.ajaxSettings.xhr();d.upload&&(c(d.upload).bind("progress",function(d){var c=d.originalEvent;d.lengthComputable=c.lengthComputable;d.loaded=c.loaded;d.total=c.total;b._onProgress(d,a)}),a.xhr=function(){return d})},_isInstanceOf:function(a,b){return Object.prototype.toString.call(b)===
"[object "+a+"]"},_initXHRData:function(a){var b=this,d,e=a.files[0],f=a.multipart||!c.support.xhrFileUpload,g="array"===c.type(a.paramName)?a.paramName[0]:a.paramName;a.headers=c.extend({},a.headers);a.contentRange&&(a.headers["Content-Range"]=a.contentRange);f&&!a.blob&&this._isInstanceOf("File",e)||(a.headers["Content-Disposition"]='attachment; filename="'+encodeURI(e.uploadName||e.name)+'"');f?c.support.xhrFormDataFileUpload&&(a.postMessage?(d=this._getFormData(a),a.blob?d.push({name:g,value:a.blob}):
c.each(a.files,function(b,e){d.push({name:"array"===c.type(a.paramName)&&a.paramName[b]||g,value:e})})):(b._isInstanceOf("FormData",a.formData)?d=a.formData:(d=new FormData,c.each(this._getFormData(a),function(a,b){d.append(b.name,b.value)})),a.blob?d.append(g,a.blob,e.uploadName||e.name):c.each(a.files,function(e,f){(b._isInstanceOf("File",f)||b._isInstanceOf("Blob",f))&&d.append("array"===c.type(a.paramName)&&a.paramName[e]||g,f,f.uploadName||f.name)})),a.data=d):(a.contentType=e.type||"application/octet-stream",
a.data=a.blob||e);a.blob=null},_initIframeSettings:function(a){var b=c("<a></a>").prop("href",a.url).prop("host");a.dataType="iframe "+(a.dataType||"");a.formData=this._getFormData(a);a.redirect&&b&&b!==location.host&&a.formData.push({name:a.redirectParamName||"redirect",value:a.redirect})},_initDataSettings:function(a){this._isXHRUpload(a)?(this._chunkedUpload(a,!0)||(a.data||this._initXHRData(a),this._initProgressListener(a)),a.postMessage&&(a.dataType="postmessage "+(a.dataType||""))):this._initIframeSettings(a)},
_getParamName:function(a){var b=c(a.fileInput),d=a.paramName;d?c.isArray(d)||(d=[d]):(d=[],b.each(function(){for(var a=c(this),b=a.prop("name")||"files[]",a=(a.prop("files")||[1]).length;a;)d.push(b),--a}),d.length||(d=[b.prop("name")||"files[]"]));return d},_initFormSettings:function(a){a.form&&a.form.length||(a.form=c(a.fileInput.prop("form")),a.form.length||(a.form=c(this.options.fileInput.prop("form"))));a.paramName=this._getParamName(a);a.url||(a.url=a.form.prop("action")||location.href);a.type=
(a.type||"string"===c.type(a.form.prop("method"))&&a.form.prop("method")||"").toUpperCase();"POST"!==a.type&&"PUT"!==a.type&&"PATCH"!==a.type&&(a.type="POST");a.formAcceptCharset||(a.formAcceptCharset=a.form.attr("accept-charset"))},_getAJAXSettings:function(a){a=c.extend({},this.options,a);this._initFormSettings(a);this._initDataSettings(a);return a},_getDeferredState:function(a){return a.state?a.state():a.isResolved()?"resolved":a.isRejected()?"rejected":"pending"},_enhancePromise:function(a){a.success=
a.done;a.error=a.fail;a.complete=a.always;return a},_getXHRPromise:function(a,b,d){var e=c.Deferred(),f=e.promise();b=b||this.options.context||f;!0===a?e.resolveWith(b,d):!1===a&&e.rejectWith(b,d);f.abort=e.promise;return this._enhancePromise(f)},_addConvenienceMethods:function(a,b){var d=this,e=function(a){return c.Deferred().resolveWith(d,a).promise()};b.process=function(a,g){if(a||g)b._processQueue=this._processQueue=(this._processQueue||e([this])).then(function(){return b.errorThrown?c.Deferred().rejectWith(d,
[b]).promise():e(arguments)}).then(a,g);return this._processQueue||e([this])};b.submit=function(){"pending"!==this.state()&&(b.jqXHR=this.jqXHR=!1!==d._trigger("submit",c.Event("submit",{delegatedEvent:a}),this)&&d._onSend(a,this));return this.jqXHR||d._getXHRPromise()};b.abort=function(){if(this.jqXHR)return this.jqXHR.abort();this.errorThrown="abort";d._trigger("fail",null,this);return d._getXHRPromise(!1)};b.state=function(){if(this.jqXHR)return d._getDeferredState(this.jqXHR);if(this._processQueue)return d._getDeferredState(this._processQueue)};
b.processing=function(){return!this.jqXHR&&this._processQueue&&"pending"===d._getDeferredState(this._processQueue)};b.progress=function(){return this._progress};b.response=function(){return this._response}},_getUploadedBytes:function(a){return(a=(a=(a=a.getResponseHeader("Range"))&&a.split("-"))&&1<a.length&&parseInt(a[1],10))&&a+1},_chunkedUpload:function(a,b){a.uploadedBytes=a.uploadedBytes||0;var d=this,e=a.files[0],f=e.size,g=a.uploadedBytes,k=a.maxChunkSize||f,h=this._blobSlice,m=c.Deferred(),
p=m.promise(),n,u;if(!(this._isXHRUpload(a)&&h&&(g||("function"===c.type(k)?k(a):k)<f))||a.data)return!1;if(b)return!0;if(g>=f)return e.error=a.i18n("uploadedBytes"),this._getXHRPromise(!1,a.context,[null,"error",e.error]);u=function(){var b=c.extend({},a),p=b._progress.loaded;b.blob=h.call(e,g,g+("function"===c.type(k)?k(b):k),e.type);b.chunkSize=b.blob.size;b.contentRange="bytes "+g+"-"+(g+b.chunkSize-1)+"/"+f;d._initXHRData(b);d._initProgressListener(b);n=(!1!==d._trigger("chunksend",null,b)&&
c.ajax(b)||d._getXHRPromise(!1,b.context)).done(function(e,h,k){g=d._getUploadedBytes(k)||g+b.chunkSize;p+b.chunkSize-b._progress.loaded&&d._onProgress(c.Event("progress",{lengthComputable:!0,loaded:g-b.uploadedBytes,total:g-b.uploadedBytes}),b);a.uploadedBytes=b.uploadedBytes=g;b.result=e;b.textStatus=h;b.jqXHR=k;d._trigger("chunkdone",null,b);d._trigger("chunkalways",null,b);g<f?u():m.resolveWith(b.context,[e,h,k])}).fail(function(a,c,e){b.jqXHR=a;b.textStatus=c;b.errorThrown=e;d._trigger("chunkfail",
null,b);d._trigger("chunkalways",null,b);m.rejectWith(b.context,[a,c,e])})};this._enhancePromise(p);p.abort=function(){return n.abort()};u();return p},_beforeSend:function(a,b){0===this._active&&(this._trigger("start"),this._bitrateTimer=new this._BitrateTimer,this._progress.loaded=this._progress.total=0,this._progress.bitrate=0);this._initResponseObject(b);this._initProgressObject(b);b._progress.loaded=b.loaded=b.uploadedBytes||0;b._progress.total=b.total=this._getTotal(b.files)||1;b._progress.bitrate=
b.bitrate=0;this._active+=1;this._progress.loaded+=b.loaded;this._progress.total+=b.total},_onDone:function(a,b,d,e){var f=e._progress.total,g=e._response;e._progress.loaded<f&&this._onProgress(c.Event("progress",{lengthComputable:!0,loaded:f,total:f}),e);g.result=e.result=a;g.textStatus=e.textStatus=b;g.jqXHR=e.jqXHR=d;this._trigger("done",null,e)},_onFail:function(a,b,d,c){var e=c._response;c.recalculateProgress&&(this._progress.loaded-=c._progress.loaded,this._progress.total-=c._progress.total);
e.jqXHR=c.jqXHR=a;e.textStatus=c.textStatus=b;e.errorThrown=c.errorThrown=d;this._trigger("fail",null,c)},_onAlways:function(a,b,c,e){this._trigger("always",null,e)},_onSend:function(a,b){b.submit||this._addConvenienceMethods(a,b);var d=this,e,f,g,k,h=d._getAJAXSettings(b),m=function(){d._sending+=1;h._bitrateTimer=new d._BitrateTimer;return e=e||((f||!1===d._trigger("send",c.Event("send",{delegatedEvent:a}),h))&&d._getXHRPromise(!1,h.context,f)||d._chunkedUpload(h)||c.ajax(h)).done(function(a,b,
c){d._onDone(a,b,c,h)}).fail(function(a,b,c){d._onFail(a,b,c,h)}).always(function(a,b,c){d._onAlways(a,b,c,h);--d._sending;--d._active;if(h.limitConcurrentUploads&&h.limitConcurrentUploads>d._sending)for(a=d._slots.shift();a;){if("pending"===d._getDeferredState(a)){a.resolve();break}a=d._slots.shift()}0===d._active&&d._trigger("stop")})};this._beforeSend(a,h);return this.options.sequentialUploads||this.options.limitConcurrentUploads&&this.options.limitConcurrentUploads<=this._sending?(1<this.options.limitConcurrentUploads?
(g=c.Deferred(),this._slots.push(g),k=g.then(m)):k=this._sequence=this._sequence.then(m,m),k.abort=function(){f=[void 0,"abort","abort"];return e?e.abort():(g&&g.rejectWith(h.context,f),m())},this._enhancePromise(k)):m()},_onAdd:function(a,b){var d=this,e=!0,f=c.extend({},this.options,b),g=b.files,k=g.length,h=f.limitMultiFileUploads,m=f.limitMultiFileUploadSize,p=f.limitMultiFileUploadSizeOverhead,n=0,l=this._getParamName(f),q,r,t=0;if(!k)return!1;m&&void 0===g[0].size&&(m=void 0);if((f.singleFileUploads||
h||m)&&this._isXHRUpload(f))if(f.singleFileUploads||m||!h)if(!f.singleFileUploads&&m)for(r=[],q=[],f=0;f<k;f+=1){if(n+=g[f].size+p,f+1===k||n+g[f+1].size+p>m||h&&f+1-t>=h)r.push(g.slice(t,f+1)),n=l.slice(t,f+1),n.length||(n=l),q.push(n),t=f+1,n=0}else q=l;else for(r=[],q=[],f=0;f<k;f+=h)r.push(g.slice(f,f+h)),n=l.slice(f,f+h),n.length||(n=l),q.push(n);else r=[g],q=[l];b.originalFiles=g;c.each(r||g,function(f,g){var h=c.extend({},b);h.files=r?g:[g];h.paramName=q[f];d._initResponseObject(h);d._initProgressObject(h);
d._addConvenienceMethods(a,h);return e=d._trigger("add",c.Event("add",{delegatedEvent:a}),h)});return e},_replaceFileInput:function(a){var b=a.fileInput,d=b.clone(!0),e=b.is(document.activeElement);a.fileInputClone=d;c("<form></form>").append(d)[0].reset();b.after(d).detach();e&&d.focus();c.cleanData(b.unbind("remove"));this.options.fileInput=this.options.fileInput.map(function(a,c){return c===b[0]?d[0]:c});b[0]===this.element[0]&&(this.element=d)},_handleFileTreeEntry:function(a,b){var d=this,e=
c.Deferred(),f=[],g,k=function(b){b&&!b.entry&&(b.entry=a);e.resolve([b])},h=function(c){d._handleFileTreeEntries(c,b+a.name+"/").done(function(a){e.resolve(a)}).fail(k)},m=function(){g.readEntries(function(a){a.length?(f=f.concat(a),m()):h(f)},k)};b=b||"";a.isFile?a._file?(a._file.relativePath=b,e.resolve(a._file)):a.file(function(a){a.relativePath=b;e.resolve(a)},k):a.isDirectory?(g=a.createReader(),m()):e.resolve([]);return e.promise()},_handleFileTreeEntries:function(a,b){var d=this;return c.when.apply(c,
c.map(a,function(a){return d._handleFileTreeEntry(a,b)})).then(function(){return Array.prototype.concat.apply([],arguments)})},_getDroppedFiles:function(a){a=a||{};var b=a.items;return b&&b.length&&(b[0].webkitGetAsEntry||b[0].getAsEntry)?this._handleFileTreeEntries(c.map(b,function(a){var b;if(a.webkitGetAsEntry){if(b=a.webkitGetAsEntry())b._file=a.getAsFile();return b}return a.getAsEntry()})):c.Deferred().resolve(c.makeArray(a.files)).promise()},_getSingleFileInputFiles:function(a){a=c(a);var b=
a.prop("webkitEntries")||a.prop("entries");if(b&&b.length)return this._handleFileTreeEntries(b);b=c.makeArray(a.prop("files"));if(b.length)void 0===b[0].name&&b[0].fileName&&c.each(b,function(a,b){b.name=b.fileName;b.size=b.fileSize});else{a=a.prop("value");if(!a)return c.Deferred().resolve([]).promise();b=[{name:a.replace(/^.*\\/,"")}]}return c.Deferred().resolve(b).promise()},_getFileInputFiles:function(a){return a instanceof c&&1!==a.length?c.when.apply(c,c.map(a,this._getSingleFileInputFiles)).then(function(){return Array.prototype.concat.apply([],
arguments)}):this._getSingleFileInputFiles(a)},_onChange:function(a){var b=this,d={fileInput:c(a.target),form:c(a.target.form)};this._getFileInputFiles(d.fileInput).always(function(e){d.files=e;b.options.replaceFileInput&&b._replaceFileInput(d);!1!==b._trigger("change",c.Event("change",{delegatedEvent:a}),d)&&b._onAdd(a,d)})},_onPaste:function(a){var b=a.originalEvent&&a.originalEvent.clipboardData&&a.originalEvent.clipboardData.items,d={files:[]};b&&b.length&&(c.each(b,function(a,b){var c=b.getAsFile&&
b.getAsFile();c&&d.files.push(c)}),!1!==this._trigger("paste",c.Event("paste",{delegatedEvent:a}),d)&&this._onAdd(a,d))},_onDrop:function(a){a.dataTransfer=a.originalEvent&&a.originalEvent.dataTransfer;var b=this,d=a.dataTransfer,e={};d&&d.files&&d.files.length&&(a.preventDefault(),this._getDroppedFiles(d).always(function(d){e.files=d;!1!==b._trigger("drop",c.Event("drop",{delegatedEvent:a}),e)&&b._onAdd(a,e)}))},_onDragOver:l("dragover"),_onDragEnter:l("dragenter"),_onDragLeave:l("dragleave"),_initEventHandlers:function(){this._isXHRUpload(this.options)&&
(this._on(this.options.dropZone,{dragover:this._onDragOver,drop:this._onDrop,dragenter:this._onDragEnter,dragleave:this._onDragLeave}),this._on(this.options.pasteZone,{paste:this._onPaste}));c.support.fileInput&&this._on(this.options.fileInput,{change:this._onChange})},_destroyEventHandlers:function(){this._off(this.options.dropZone,"dragenter dragleave dragover drop");this._off(this.options.pasteZone,"paste");this._off(this.options.fileInput,"change")},_destroy:function(){this._destroyEventHandlers()},
_setOption:function(a,b){var d=-1!==c.inArray(a,this._specialOptions);d&&this._destroyEventHandlers();this._super(a,b);d&&(this._initSpecialOptions(),this._initEventHandlers())},_initSpecialOptions:function(){var a=this.options;void 0===a.fileInput?a.fileInput=this.element.is('input[type="file"]')?this.element:this.element.find('input[type="file"]'):a.fileInput instanceof c||(a.fileInput=c(a.fileInput));a.dropZone instanceof c||(a.dropZone=c(a.dropZone));a.pasteZone instanceof c||(a.pasteZone=c(a.pasteZone))},
_getRegExp:function(a){a=a.split("/");var b=a.pop();a.shift();return new RegExp(a.join("/"),b)},_isRegExpOption:function(a,b){return"url"!==a&&"string"===c.type(b)&&/^\/.*\/[igm]{0,3}$/.test(b)},_initDataAttributes:function(){var a=this,b=this.options,d=this.element.data();c.each(this.element[0].attributes,function(c,f){var e=f.name.toLowerCase(),k;/^data-/.test(e)&&(e=e.slice(5).replace(/-[a-z]/g,function(a){return a.charAt(1).toUpperCase()}),k=d[e],a._isRegExpOption(e,k)&&(k=a._getRegExp(k)),b[e]=
k)})},_create:function(){this._initDataAttributes();this._initSpecialOptions();this._slots=[];this._sequence=this._getXHRPromise(!0);this._sending=this._active=0;this._initProgressObject(this);this._initEventHandlers()},active:function(){return this._active},progress:function(){return this._progress},add:function(a){var b=this;a&&!this.options.disabled&&(a.fileInput&&!a.files?this._getFileInputFiles(a.fileInput).always(function(c){a.files=c;b._onAdd(null,a)}):(a.files=c.makeArray(a.files),this._onAdd(null,
a)))},send:function(a){if(a&&!this.options.disabled){if(a.fileInput&&!a.files){var b=this,d=c.Deferred(),e=d.promise(),f,g;e.abort=function(){g=!0;if(f)return f.abort();d.reject(null,"abort","abort");return e};this._getFileInputFiles(a.fileInput).always(function(c){g||(c.length?(a.files=c,f=b._onSend(null,a),f.then(function(a,b,c){d.resolve(a,b,c)},function(a,b,c){d.reject(a,b,c)})):d.reject())});return this._enhancePromise(e)}a.files=c.makeArray(a.files);if(a.files.length)return this._onSend(null,
a)}return this._getXHRPromise(!1,a&&a.context)}})});
