var $jscomp={scope:{},findInternal:function(a,c,b){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(c.call(b,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in b||(b[e]={});b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6-impl","es3");
var ria_chat_manager={init:function(){this.updateTime=12E4;this.$chat=$("#widgetRChat");if(0>=this.$chat.length)return!1;this.mod={view_list:"m-view-list",no_list:"m-no-list"};this.$title=$(".widgets__r-header-one span",this.$live);this.$loader=$(".widgets__r-loader",this.$chat);this.$list=$(".widgets__r-list",this.$chat);this.$back=$(".widgets__r-header-button.m-back",this.$chat);this.checkActive();this.addEvents();this.updateUnread()},addEvents:function(){var a=this;a.$list.on("click",".r-list__item",
function(){a.toArticleRoom||(window.dataLayer=window.dataLayer||[],dataLayer.push({event:"chat",gaEventAction:"chat_click",gaEventLabel:"main"}));a.toOnline($(this))});a.$back.on("click",function(){a.toList()});$(".js__toggle-chat").on("click",function(){setTimeout(function(){a.$chat.hasClass(a.mod.view_list)&&a.$chat.is(":visible")?(a.updateRooms(),a.setNotification(Notifications.isAllChatsDisabled())):a.stopUpdateRooms()},0)});$("body").on("click",".js__toggle-chat-article",function(){var c=$(this),
b=null;c.data("article_id")?b=c.data("article_id"):GLOBAL.article&&GLOBAL.article.id&&(b=GLOBAL.article.id);a.openArticleRoom(b)});$("body").on("click",".best-comments__btn",function(){window.dataLayer=window.dataLayer||[];dataLayer.push({event:"chat",gaEventAction:"chat_open",gaEventLabel:"popular_comments"})});$("body").on("click",".article__userbar-item.m-discuss",function(){window.dataLayer=window.dataLayer||[];dataLayer.push({event:"chat",gaEventAction:"chat_open",gaEventLabel:"main_comments"})});
a.$chat.on("click","#chatNotificationOn, #chatNotificationOff",function(){a.$chat.hasClass(a.mod.view_list)?Notifications.setAllChats(Notifications.isAllChatsDisabled()?1:0):Notifications.setChatRoom(ria_chat.state.article_id,Notifications.isRoomDisabled(ria_chat.state.article_id)?1:0);$(this).hide().siblings().show()});setTimeout(function(){a.$chat.find(".r-list__wr").trigger("add-scrolling-trigger.the-in-scroll",[{name:"scroll_end",position:"99%",sign:">",down:!1,everytime:!0,move:!0,once:!0}]);
a.$chat.find(".r-list__wr").on("scroll_end.the-in-scroll",function(){window.dataLayer=window.dataLayer||[];dataLayer.push({event:"chat",gaEventAction:"chat_scroll",gaEventLabel:"main"})})},0)},checkActive:function(){this.$chat.hasClass(this.mod.view_list)||0>=this.$list.length&&this.$chat.addClass(this.mod.no_list)},toList:function(){this.$chat.addClass(this.mod.view_list);this.setNotification(Notifications.isAllChatsDisabled());ria_chat&&(ria_chat.left(),this.updateRooms())},toOnline:function(a){this.setTitle(a.data("title"));
if(a.data("url"))this.$title.on("click",function(){window.location.href=a.data("url")});GLOBAL.article&&GLOBAL.article.id===a.data("id")&&GLOBAL.article.chat_expired?$(".chat__expired").show():$(".chat__expired").hide();this.$chat.removeClass(this.mod.view_list);"object"==typeof a&&(ria_chat.join(a.data("id")),this.stopUpdateRooms(),this.setNotification(Notifications.isRoomDisabled(a.data("id"))))},setTitle:function(a){return this.$title?this.$title.html(a):!1},setNotification:function(a){$("#chatNotificationOn").toggle(!a);
$("#chatNotificationOff").toggle(a)},auth:function(){this.$chat.hasClass(this.mod.view_list)?this.setNotification(Notifications.isAllChatsDisabled()):this.setNotification(Notifications.isRoomDisabled(ria_chat.state.article_id))},getRooms:function(){var a="/services/chat/get_rooms/",c=this.toArticleRoom||GLOBAL.article&&GLOBAL.article.id;c&&(a+="?cur_room_id="+c);return $.ajax({url:a})},insertRooms:function(a){a&&this.$chat.find(".r-list, .r-list__wr").css({position:"absolute",top:"0",width:"100%",
height:"100%"}).trigger("clear-content.the-in-scroll").trigger("add-content.the-in-scroll",[a,!0])},getUnread:function(){},updateUnread:function(){this.stopUpdateUnread();this.getUnread()},stopUpdateUnread:function(){this.getUnreadInterval&&clearInterval(this.getUnreadInterval)},updateRooms:function(){var a=this;a.stopUpdateRooms();a.getRooms().done(function(c){a.insertRooms(c);a.toArticleRoom&&setTimeout(function(){a.showArticleRoom(a.toArticleRoom)},0)})},stopUpdateRooms:function(){this.getRoomsInterval&&
clearInterval(this.getRoomsInterval)},openArticleRoom:function(a){this.toArticleRoom=a;this.$chat.is(":visible")?this.$chat.hasClass(this.mod.view_list)?this.toArticleRoom&&this.showArticleRoom(this.toArticleRoom):this.toList():$(".js__toggle-chat").eq(0).trigger("click")},showArticleRoom:function(a){this.$list.find(".r-list__item").filter('[data-id="'+a+'"]').trigger("click");this.toArticleRoom=!1}};$(function(){ria_chat_manager.init()});
